/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "base_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace braft {

int _kThriftEntryTypeValues[] = {
  ThriftEntryType::ENTRY_TYPE_UNKNOWN,
  ThriftEntryType::ENTRY_TYPE_NO_OP,
  ThriftEntryType::ENTRY_TYPE_DATA,
  ThriftEntryType::ENTRY_TYPE_CONFIGURATION
};
const char* _kThriftEntryTypeNames[] = {
  "ENTRY_TYPE_UNKNOWN",
  "ENTRY_TYPE_NO_OP",
  "ENTRY_TYPE_DATA",
  "ENTRY_TYPE_CONFIGURATION"
};
const std::map<int, const char*> _ThriftEntryType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kThriftEntryTypeValues, _kThriftEntryTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ThriftEntryType::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftEntryType_VALUES_TO_NAMES.find(val);
  if (it != _ThriftEntryType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ThriftEntryType::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftEntryType_VALUES_TO_NAMES.find(val);
  if (it != _ThriftEntryType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kThriftErrorTypeValues[] = {
  ThriftErrorType::ERROR_TYPE_NONE,
  ThriftErrorType::ERROR_TYPE_LOG,
  ThriftErrorType::ERROR_TYPE_STABLE,
  ThriftErrorType::ERROR_TYPE_SNAPSHOT,
  ThriftErrorType::ERROR_TYPE_STATE_MACHINE
};
const char* _kThriftErrorTypeNames[] = {
  "ERROR_TYPE_NONE",
  "ERROR_TYPE_LOG",
  "ERROR_TYPE_STABLE",
  "ERROR_TYPE_SNAPSHOT",
  "ERROR_TYPE_STATE_MACHINE"
};
const std::map<int, const char*> _ThriftErrorType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kThriftErrorTypeValues, _kThriftErrorTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ThriftErrorType::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftErrorType_VALUES_TO_NAMES.find(val);
  if (it != _ThriftErrorType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ThriftErrorType::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftErrorType_VALUES_TO_NAMES.find(val);
  if (it != _ThriftErrorType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kThriftRaftErrorValues[] = {
  ThriftRaftError::ERAFTTIMEDOUT,
  ThriftRaftError::ESTATEMACHINE,
  ThriftRaftError::ECATCHUP,
  ThriftRaftError::ELEADERREMOVED,
  ThriftRaftError::ESETPEER,
  ThriftRaftError::ENODESHUTDOWN,
  ThriftRaftError::EHIGHERTERMREQUEST,
  ThriftRaftError::EHIGHERTERMRESPONSE,
  ThriftRaftError::EBADNODE,
  ThriftRaftError::EVOTEFORCANDIDATE,
  ThriftRaftError::ENEWLEADER,
  ThriftRaftError::ELEADERCONFLICT,
  ThriftRaftError::ETRANSFERLEADERSHIP,
  ThriftRaftError::ELOGDELETED,
  ThriftRaftError::ENOMOREUSERLOG,
  ThriftRaftError::EREADONLY
};
const char* _kThriftRaftErrorNames[] = {
  "ERAFTTIMEDOUT",
  "ESTATEMACHINE",
  "ECATCHUP",
  "ELEADERREMOVED",
  "ESETPEER",
  "ENODESHUTDOWN",
  "EHIGHERTERMREQUEST",
  "EHIGHERTERMRESPONSE",
  "EBADNODE",
  "EVOTEFORCANDIDATE",
  "ENEWLEADER",
  "ELEADERCONFLICT",
  "ETRANSFERLEADERSHIP",
  "ELOGDELETED",
  "ENOMOREUSERLOG",
  "EREADONLY"
};
const std::map<int, const char*> _ThriftRaftError_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(16, _kThriftRaftErrorValues, _kThriftRaftErrorNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ThriftRaftError::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftRaftError_VALUES_TO_NAMES.find(val);
  if (it != _ThriftRaftError_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ThriftRaftError::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftRaftError_VALUES_TO_NAMES.find(val);
  if (it != _ThriftRaftError_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


TermLeader::~TermLeader() noexcept {
}


void TermLeader::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}

void TermLeader::__set_term(const int64_t val) {
  this->term = val;
}
std::ostream& operator<<(std::ostream& out, const TermLeader& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TermLeader::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TermLeader::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TermLeader");

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TermLeader &a, TermLeader &b) {
  using ::std::swap;
  swap(a.peer_id, b.peer_id);
  swap(a.term, b.term);
  swap(a.__isset, b.__isset);
}

TermLeader::TermLeader(const TermLeader& other0) {
  peer_id = other0.peer_id;
  term = other0.term;
  __isset = other0.__isset;
}
TermLeader& TermLeader::operator=(const TermLeader& other1) {
  peer_id = other1.peer_id;
  term = other1.term;
  __isset = other1.__isset;
  return *this;
}
void TermLeader::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TermLeader(";
  out << "peer_id=" << to_string(peer_id);
  out << ", " << "term=" << to_string(term);
  out << ")";
}


EntryMeta::~EntryMeta() noexcept {
}


void EntryMeta::__set_term(const int64_t val) {
  this->term = val;
}

void EntryMeta::__set_type(const ThriftEntryType::type val) {
  this->type = val;
}

void EntryMeta::__set_peers(const std::vector<std::string> & val) {
  this->peers = val;
}

void EntryMeta::__set_data_len(const int64_t val) {
  this->data_len = val;
__isset.data_len = true;
}

void EntryMeta::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}
std::ostream& operator<<(std::ostream& out, const EntryMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t EntryMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->type = static_cast<ThriftEntryType::type>(ecast2);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->peers.clear();
            uint32_t _size3;
            ::apache::thrift::protocol::TType _etype6;
            xfer += iprot->readListBegin(_etype6, _size3);
            this->peers.resize(_size3);
            uint32_t _i7;
            for (_i7 = 0; _i7 < _size3; ++_i7)
            {
              xfer += iprot->readString(this->peers[_i7]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->data_len);
          this->__isset.data_len = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size8;
            ::apache::thrift::protocol::TType _etype11;
            xfer += iprot->readListBegin(_etype11, _size8);
            this->old_peers.resize(_size8);
            uint32_t _i12;
            for (_i12 = 0; _i12 < _size8; ++_i12)
            {
              xfer += iprot->readString(this->old_peers[_i12]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t EntryMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("EntryMeta");

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(static_cast<int32_t>(this->type));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peers", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->peers.size()));
    std::vector<std::string> ::const_iterator _iter13;
    for (_iter13 = this->peers.begin(); _iter13 != this->peers.end(); ++_iter13)
    {
      xfer += oprot->writeString((*_iter13));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  if (this->__isset.data_len) {
    xfer += oprot->writeFieldBegin("data_len", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->data_len);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter14;
    for (_iter14 = this->old_peers.begin(); _iter14 != this->old_peers.end(); ++_iter14)
    {
      xfer += oprot->writeString((*_iter14));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(EntryMeta &a, EntryMeta &b) {
  using ::std::swap;
  swap(a.term, b.term);
  swap(a.type, b.type);
  swap(a.peers, b.peers);
  swap(a.data_len, b.data_len);
  swap(a.old_peers, b.old_peers);
  swap(a.__isset, b.__isset);
}

EntryMeta::EntryMeta(const EntryMeta& other15) {
  term = other15.term;
  type = other15.type;
  peers = other15.peers;
  data_len = other15.data_len;
  old_peers = other15.old_peers;
  __isset = other15.__isset;
}
EntryMeta& EntryMeta::operator=(const EntryMeta& other16) {
  term = other16.term;
  type = other16.type;
  peers = other16.peers;
  data_len = other16.data_len;
  old_peers = other16.old_peers;
  __isset = other16.__isset;
  return *this;
}
void EntryMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "EntryMeta(";
  out << "term=" << to_string(term);
  out << ", " << "type=" << to_string(type);
  out << ", " << "peers=" << to_string(peers);
  out << ", " << "data_len="; (__isset.data_len ? (out << to_string(data_len)) : (out << "<null>"));
  out << ", " << "old_peers=" << to_string(old_peers);
  out << ")";
}


SnapshotMeta::~SnapshotMeta() noexcept {
}


void SnapshotMeta::__set_last_included_index(const int64_t val) {
  this->last_included_index = val;
}

void SnapshotMeta::__set_last_included_term(const int64_t val) {
  this->last_included_term = val;
}

void SnapshotMeta::__set_peers(const std::vector<std::string> & val) {
  this->peers = val;
}

void SnapshotMeta::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}
std::ostream& operator<<(std::ostream& out, const SnapshotMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SnapshotMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->last_included_index);
          this->__isset.last_included_index = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->last_included_term);
          this->__isset.last_included_term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->peers.clear();
            uint32_t _size17;
            ::apache::thrift::protocol::TType _etype20;
            xfer += iprot->readListBegin(_etype20, _size17);
            this->peers.resize(_size17);
            uint32_t _i21;
            for (_i21 = 0; _i21 < _size17; ++_i21)
            {
              xfer += iprot->readString(this->peers[_i21]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size22;
            ::apache::thrift::protocol::TType _etype25;
            xfer += iprot->readListBegin(_etype25, _size22);
            this->old_peers.resize(_size22);
            uint32_t _i26;
            for (_i26 = 0; _i26 < _size22; ++_i26)
            {
              xfer += iprot->readString(this->old_peers[_i26]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SnapshotMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SnapshotMeta");

  xfer += oprot->writeFieldBegin("last_included_index", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->last_included_index);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("last_included_term", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->last_included_term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peers", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->peers.size()));
    std::vector<std::string> ::const_iterator _iter27;
    for (_iter27 = this->peers.begin(); _iter27 != this->peers.end(); ++_iter27)
    {
      xfer += oprot->writeString((*_iter27));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter28;
    for (_iter28 = this->old_peers.begin(); _iter28 != this->old_peers.end(); ++_iter28)
    {
      xfer += oprot->writeString((*_iter28));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SnapshotMeta &a, SnapshotMeta &b) {
  using ::std::swap;
  swap(a.last_included_index, b.last_included_index);
  swap(a.last_included_term, b.last_included_term);
  swap(a.peers, b.peers);
  swap(a.old_peers, b.old_peers);
  swap(a.__isset, b.__isset);
}

SnapshotMeta::SnapshotMeta(const SnapshotMeta& other29) {
  last_included_index = other29.last_included_index;
  last_included_term = other29.last_included_term;
  peers = other29.peers;
  old_peers = other29.old_peers;
  __isset = other29.__isset;
}
SnapshotMeta& SnapshotMeta::operator=(const SnapshotMeta& other30) {
  last_included_index = other30.last_included_index;
  last_included_term = other30.last_included_term;
  peers = other30.peers;
  old_peers = other30.old_peers;
  __isset = other30.__isset;
  return *this;
}
void SnapshotMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SnapshotMeta(";
  out << "last_included_index=" << to_string(last_included_index);
  out << ", " << "last_included_term=" << to_string(last_included_term);
  out << ", " << "peers=" << to_string(peers);
  out << ", " << "old_peers=" << to_string(old_peers);
  out << ")";
}

} // namespace
