/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef base_TYPES_H
#define base_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace braft {

/**
 * EntryType - Log entry type enumeration
 * Maps to braft/enum.proto EntryType
 */
struct EntryType {
  enum type {
    ENTRY_TYPE_UNKNOWN = 0,
    ENTRY_TYPE_NO_OP = 1,
    ENTRY_TYPE_DATA = 2,
    ENTRY_TYPE_CONFIGURATION = 3
  };
};

extern const std::map<int, const char*> _EntryType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const EntryType::type& val);

std::string to_string(const EntryType::type& val);

/**
 * ErrorType - Error type enumeration
 * Maps to braft/enum.proto ErrorType
 */
struct ErrorType {
  enum type {
    ERROR_TYPE_NONE = 0,
    ERROR_TYPE_LOG = 1,
    ERROR_TYPE_STABLE = 2,
    ERROR_TYPE_SNAPSHOT = 3,
    ERROR_TYPE_STATE_MACHINE = 4
  };
};

extern const std::map<int, const char*> _ErrorType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ErrorType::type& val);

std::string to_string(const ErrorType::type& val);

/**
 * RaftError - Raft specific error codes
 * Maps to braft/errno.proto RaftError
 * Error codes start from 10000 to avoid conflicts with HTTP and RPC errors
 */
struct RaftError {
  enum type {
    ERAFTTIMEDOUT = 10001,
    ESTATEMACHINE = 10002,
    ECATCHUP = 10003,
    ELEADERREMOVED = 10004,
    ESETPEER = 10005,
    ENODESHUTDOWN = 10006,
    EHIGHERTERMREQUEST = 10007,
    EHIGHERTERMRESPONSE = 10008,
    EBADNODE = 10009,
    EVOTEFORCANDIDATE = 10010,
    ENEWLEADER = 10011,
    ELEADERCONFLICT = 10012,
    ETRANSFERLEADERSHIP = 10013,
    ELOGDELETED = 10014,
    ENOMOREUSERLOG = 10015,
    EREADONLY = 10016
  };
};

extern const std::map<int, const char*> _RaftError_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const RaftError::type& val);

std::string to_string(const RaftError::type& val);

class TermLeader;

class EntryMeta;

class SnapshotMeta;

typedef struct _TermLeader__isset {
  _TermLeader__isset() : peer_id(false), term(false) {}
  bool peer_id :1;
  bool term :1;
} _TermLeader__isset;

/**
 * TermLeader - Represents a leader in a specific term
 * Used for disrupted leader detection
 */
class TermLeader : public virtual ::apache::thrift::TBase {
 public:

  TermLeader(const TermLeader&);
  TermLeader& operator=(const TermLeader&);
  TermLeader() noexcept
             : peer_id(),
               term(0) {
  }

  virtual ~TermLeader() noexcept;
  std::string peer_id;
  int64_t term;

  _TermLeader__isset __isset;

  void __set_peer_id(const std::string& val);

  void __set_term(const int64_t val);

  bool operator == (const TermLeader & rhs) const
  {
    if (!(peer_id == rhs.peer_id))
      return false;
    if (!(term == rhs.term))
      return false;
    return true;
  }
  bool operator != (const TermLeader &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TermLeader & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TermLeader &a, TermLeader &b);

std::ostream& operator<<(std::ostream& out, const TermLeader& obj);

typedef struct _EntryMeta__isset {
  _EntryMeta__isset() : term(false), type(false), peers(false), data_len(false), old_peers(false) {}
  bool term :1;
  bool type :1;
  bool peers :1;
  bool data_len :1;
  bool old_peers :1;
} _EntryMeta__isset;

/**
 * EntryMeta - Metadata for a log entry
 * Stored in brpc attachment for efficiency
 */
class EntryMeta : public virtual ::apache::thrift::TBase {
 public:

  EntryMeta(const EntryMeta&);
  EntryMeta& operator=(const EntryMeta&);
  EntryMeta() noexcept
            : term(0),
              type(static_cast<EntryType::type>(0)),
              data_len(0) {
  }

  virtual ~EntryMeta() noexcept;
  int64_t term;
  /**
   * 
   * @see EntryType
   */
  EntryType::type type;
  std::vector<std::string>  peers;
  int64_t data_len;
  std::vector<std::string>  old_peers;

  _EntryMeta__isset __isset;

  void __set_term(const int64_t val);

  void __set_type(const EntryType::type val);

  void __set_peers(const std::vector<std::string> & val);

  void __set_data_len(const int64_t val);

  void __set_old_peers(const std::vector<std::string> & val);

  bool operator == (const EntryMeta & rhs) const
  {
    if (!(term == rhs.term))
      return false;
    if (!(type == rhs.type))
      return false;
    if (!(peers == rhs.peers))
      return false;
    if (__isset.data_len != rhs.__isset.data_len)
      return false;
    else if (__isset.data_len && !(data_len == rhs.data_len))
      return false;
    if (!(old_peers == rhs.old_peers))
      return false;
    return true;
  }
  bool operator != (const EntryMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EntryMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(EntryMeta &a, EntryMeta &b);

std::ostream& operator<<(std::ostream& out, const EntryMeta& obj);

typedef struct _SnapshotMeta__isset {
  _SnapshotMeta__isset() : last_included_index(false), last_included_term(false), peers(false), old_peers(false) {}
  bool last_included_index :1;
  bool last_included_term :1;
  bool peers :1;
  bool old_peers :1;
} _SnapshotMeta__isset;

/**
 * SnapshotMeta - Metadata for a snapshot
 * Contains the last included index/term and configuration
 */
class SnapshotMeta : public virtual ::apache::thrift::TBase {
 public:

  SnapshotMeta(const SnapshotMeta&);
  SnapshotMeta& operator=(const SnapshotMeta&);
  SnapshotMeta() noexcept
               : last_included_index(0),
                 last_included_term(0) {
  }

  virtual ~SnapshotMeta() noexcept;
  int64_t last_included_index;
  int64_t last_included_term;
  std::vector<std::string>  peers;
  std::vector<std::string>  old_peers;

  _SnapshotMeta__isset __isset;

  void __set_last_included_index(const int64_t val);

  void __set_last_included_term(const int64_t val);

  void __set_peers(const std::vector<std::string> & val);

  void __set_old_peers(const std::vector<std::string> & val);

  bool operator == (const SnapshotMeta & rhs) const
  {
    if (!(last_included_index == rhs.last_included_index))
      return false;
    if (!(last_included_term == rhs.last_included_term))
      return false;
    if (!(peers == rhs.peers))
      return false;
    if (!(old_peers == rhs.old_peers))
      return false;
    return true;
  }
  bool operator != (const SnapshotMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SnapshotMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SnapshotMeta &a, SnapshotMeta &b);

std::ostream& operator<<(std::ostream& out, const SnapshotMeta& obj);

} // namespace

#endif
