/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cli_service_TYPES_H
#define cli_service_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace braft {

class AddPeerRequest;

class AddPeerResponse;

class RemovePeerRequest;

class RemovePeerResponse;

class ChangePeersRequest;

class ChangePeersResponse;

class ResetPeerRequest;

class ResetPeerResponse;

class SnapshotRequest;

class SnapshotResponse;

class TransferLeaderRequest;

class TransferLeaderResponse;

class GetLeaderRequest;

class GetLeaderResponse;

typedef struct _AddPeerRequest__isset {
  _AddPeerRequest__isset() : group_id(false), leader_id(false), peer_id(false) {}
  bool group_id :1;
  bool leader_id :1;
  bool peer_id :1;
} _AddPeerRequest__isset;

/**
 * AddPeerRequest - Add a single peer to the cluster
 */
class AddPeerRequest : public virtual ::apache::thrift::TBase {
 public:

  AddPeerRequest(const AddPeerRequest&);
  AddPeerRequest& operator=(const AddPeerRequest&);
  AddPeerRequest() noexcept
                 : group_id(),
                   leader_id(),
                   peer_id() {
  }

  virtual ~AddPeerRequest() noexcept;
  std::string group_id;
  std::string leader_id;
  std::string peer_id;

  _AddPeerRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_leader_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  bool operator == (const AddPeerRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(leader_id == rhs.leader_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    return true;
  }
  bool operator != (const AddPeerRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AddPeerRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AddPeerRequest &a, AddPeerRequest &b);

std::ostream& operator<<(std::ostream& out, const AddPeerRequest& obj);

typedef struct _AddPeerResponse__isset {
  _AddPeerResponse__isset() : old_peers(false), new_peers(false) {}
  bool old_peers :1;
  bool new_peers :1;
} _AddPeerResponse__isset;

/**
 * AddPeerResponse - Result of add_peer operation
 */
class AddPeerResponse : public virtual ::apache::thrift::TBase {
 public:

  AddPeerResponse(const AddPeerResponse&);
  AddPeerResponse& operator=(const AddPeerResponse&);
  AddPeerResponse() noexcept {
  }

  virtual ~AddPeerResponse() noexcept;
  std::vector<std::string>  old_peers;
  std::vector<std::string>  new_peers;

  _AddPeerResponse__isset __isset;

  void __set_old_peers(const std::vector<std::string> & val);

  void __set_new_peers(const std::vector<std::string> & val);

  bool operator == (const AddPeerResponse & rhs) const
  {
    if (!(old_peers == rhs.old_peers))
      return false;
    if (!(new_peers == rhs.new_peers))
      return false;
    return true;
  }
  bool operator != (const AddPeerResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AddPeerResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AddPeerResponse &a, AddPeerResponse &b);

std::ostream& operator<<(std::ostream& out, const AddPeerResponse& obj);

typedef struct _RemovePeerRequest__isset {
  _RemovePeerRequest__isset() : group_id(false), leader_id(false), peer_id(false) {}
  bool group_id :1;
  bool leader_id :1;
  bool peer_id :1;
} _RemovePeerRequest__isset;

/**
 * RemovePeerRequest - Remove a single peer from the cluster
 */
class RemovePeerRequest : public virtual ::apache::thrift::TBase {
 public:

  RemovePeerRequest(const RemovePeerRequest&);
  RemovePeerRequest& operator=(const RemovePeerRequest&);
  RemovePeerRequest() noexcept
                    : group_id(),
                      leader_id(),
                      peer_id() {
  }

  virtual ~RemovePeerRequest() noexcept;
  std::string group_id;
  std::string leader_id;
  std::string peer_id;

  _RemovePeerRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_leader_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  bool operator == (const RemovePeerRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(leader_id == rhs.leader_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    return true;
  }
  bool operator != (const RemovePeerRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemovePeerRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RemovePeerRequest &a, RemovePeerRequest &b);

std::ostream& operator<<(std::ostream& out, const RemovePeerRequest& obj);

typedef struct _RemovePeerResponse__isset {
  _RemovePeerResponse__isset() : old_peers(false), new_peers(false) {}
  bool old_peers :1;
  bool new_peers :1;
} _RemovePeerResponse__isset;

/**
 * RemovePeerResponse - Result of remove_peer operation
 */
class RemovePeerResponse : public virtual ::apache::thrift::TBase {
 public:

  RemovePeerResponse(const RemovePeerResponse&);
  RemovePeerResponse& operator=(const RemovePeerResponse&);
  RemovePeerResponse() noexcept {
  }

  virtual ~RemovePeerResponse() noexcept;
  std::vector<std::string>  old_peers;
  std::vector<std::string>  new_peers;

  _RemovePeerResponse__isset __isset;

  void __set_old_peers(const std::vector<std::string> & val);

  void __set_new_peers(const std::vector<std::string> & val);

  bool operator == (const RemovePeerResponse & rhs) const
  {
    if (!(old_peers == rhs.old_peers))
      return false;
    if (!(new_peers == rhs.new_peers))
      return false;
    return true;
  }
  bool operator != (const RemovePeerResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RemovePeerResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RemovePeerResponse &a, RemovePeerResponse &b);

std::ostream& operator<<(std::ostream& out, const RemovePeerResponse& obj);

typedef struct _ChangePeersRequest__isset {
  _ChangePeersRequest__isset() : group_id(false), leader_id(false), new_peers(false) {}
  bool group_id :1;
  bool leader_id :1;
  bool new_peers :1;
} _ChangePeersRequest__isset;

/**
 * ChangePeersRequest - Replace entire peer configuration
 */
class ChangePeersRequest : public virtual ::apache::thrift::TBase {
 public:

  ChangePeersRequest(const ChangePeersRequest&);
  ChangePeersRequest& operator=(const ChangePeersRequest&);
  ChangePeersRequest() noexcept
                     : group_id(),
                       leader_id() {
  }

  virtual ~ChangePeersRequest() noexcept;
  std::string group_id;
  std::string leader_id;
  std::vector<std::string>  new_peers;

  _ChangePeersRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_leader_id(const std::string& val);

  void __set_new_peers(const std::vector<std::string> & val);

  bool operator == (const ChangePeersRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(leader_id == rhs.leader_id))
      return false;
    if (!(new_peers == rhs.new_peers))
      return false;
    return true;
  }
  bool operator != (const ChangePeersRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChangePeersRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ChangePeersRequest &a, ChangePeersRequest &b);

std::ostream& operator<<(std::ostream& out, const ChangePeersRequest& obj);

typedef struct _ChangePeersResponse__isset {
  _ChangePeersResponse__isset() : old_peers(false), new_peers(false) {}
  bool old_peers :1;
  bool new_peers :1;
} _ChangePeersResponse__isset;

/**
 * ChangePeersResponse - Result of change_peers operation
 */
class ChangePeersResponse : public virtual ::apache::thrift::TBase {
 public:

  ChangePeersResponse(const ChangePeersResponse&);
  ChangePeersResponse& operator=(const ChangePeersResponse&);
  ChangePeersResponse() noexcept {
  }

  virtual ~ChangePeersResponse() noexcept;
  std::vector<std::string>  old_peers;
  std::vector<std::string>  new_peers;

  _ChangePeersResponse__isset __isset;

  void __set_old_peers(const std::vector<std::string> & val);

  void __set_new_peers(const std::vector<std::string> & val);

  bool operator == (const ChangePeersResponse & rhs) const
  {
    if (!(old_peers == rhs.old_peers))
      return false;
    if (!(new_peers == rhs.new_peers))
      return false;
    return true;
  }
  bool operator != (const ChangePeersResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChangePeersResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ChangePeersResponse &a, ChangePeersResponse &b);

std::ostream& operator<<(std::ostream& out, const ChangePeersResponse& obj);

typedef struct _ResetPeerRequest__isset {
  _ResetPeerRequest__isset() : group_id(false), peer_id(false), old_peers(false), new_peers(false) {}
  bool group_id :1;
  bool peer_id :1;
  bool old_peers :1;
  bool new_peers :1;
} _ResetPeerRequest__isset;

/**
 * ResetPeerRequest - Reset peer configuration (used for recovery)
 * Forces a node to adopt a specific configuration
 */
class ResetPeerRequest : public virtual ::apache::thrift::TBase {
 public:

  ResetPeerRequest(const ResetPeerRequest&);
  ResetPeerRequest& operator=(const ResetPeerRequest&);
  ResetPeerRequest() noexcept
                   : group_id(),
                     peer_id() {
  }

  virtual ~ResetPeerRequest() noexcept;
  std::string group_id;
  std::string peer_id;
  std::vector<std::string>  old_peers;
  std::vector<std::string>  new_peers;

  _ResetPeerRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  void __set_old_peers(const std::vector<std::string> & val);

  void __set_new_peers(const std::vector<std::string> & val);

  bool operator == (const ResetPeerRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    if (!(old_peers == rhs.old_peers))
      return false;
    if (!(new_peers == rhs.new_peers))
      return false;
    return true;
  }
  bool operator != (const ResetPeerRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ResetPeerRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ResetPeerRequest &a, ResetPeerRequest &b);

std::ostream& operator<<(std::ostream& out, const ResetPeerRequest& obj);


/**
 * ResetPeerResponse - Result of reset_peer operation
 */
class ResetPeerResponse : public virtual ::apache::thrift::TBase {
 public:

  ResetPeerResponse(const ResetPeerResponse&) noexcept;
  ResetPeerResponse& operator=(const ResetPeerResponse&) noexcept;
  ResetPeerResponse() noexcept {
  }

  virtual ~ResetPeerResponse() noexcept;

  bool operator == (const ResetPeerResponse & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ResetPeerResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ResetPeerResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ResetPeerResponse &a, ResetPeerResponse &b);

std::ostream& operator<<(std::ostream& out, const ResetPeerResponse& obj);

typedef struct _SnapshotRequest__isset {
  _SnapshotRequest__isset() : group_id(false), peer_id(false) {}
  bool group_id :1;
  bool peer_id :1;
} _SnapshotRequest__isset;

/**
 * SnapshotRequest - Trigger snapshot creation
 */
class SnapshotRequest : public virtual ::apache::thrift::TBase {
 public:

  SnapshotRequest(const SnapshotRequest&);
  SnapshotRequest& operator=(const SnapshotRequest&);
  SnapshotRequest() noexcept
                  : group_id(),
                    peer_id() {
  }

  virtual ~SnapshotRequest() noexcept;
  std::string group_id;
  std::string peer_id;

  _SnapshotRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  bool operator == (const SnapshotRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (__isset.peer_id != rhs.__isset.peer_id)
      return false;
    else if (__isset.peer_id && !(peer_id == rhs.peer_id))
      return false;
    return true;
  }
  bool operator != (const SnapshotRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SnapshotRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SnapshotRequest &a, SnapshotRequest &b);

std::ostream& operator<<(std::ostream& out, const SnapshotRequest& obj);


/**
 * SnapshotResponse - Result of snapshot operation
 */
class SnapshotResponse : public virtual ::apache::thrift::TBase {
 public:

  SnapshotResponse(const SnapshotResponse&) noexcept;
  SnapshotResponse& operator=(const SnapshotResponse&) noexcept;
  SnapshotResponse() noexcept {
  }

  virtual ~SnapshotResponse() noexcept;

  bool operator == (const SnapshotResponse & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SnapshotResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SnapshotResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SnapshotResponse &a, SnapshotResponse &b);

std::ostream& operator<<(std::ostream& out, const SnapshotResponse& obj);

typedef struct _TransferLeaderRequest__isset {
  _TransferLeaderRequest__isset() : group_id(false), leader_id(false), peer_id(false) {}
  bool group_id :1;
  bool leader_id :1;
  bool peer_id :1;
} _TransferLeaderRequest__isset;

/**
 * TransferLeaderRequest - Transfer leadership to another peer
 */
class TransferLeaderRequest : public virtual ::apache::thrift::TBase {
 public:

  TransferLeaderRequest(const TransferLeaderRequest&);
  TransferLeaderRequest& operator=(const TransferLeaderRequest&);
  TransferLeaderRequest() noexcept
                        : group_id(),
                          leader_id(),
                          peer_id() {
  }

  virtual ~TransferLeaderRequest() noexcept;
  std::string group_id;
  std::string leader_id;
  std::string peer_id;

  _TransferLeaderRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_leader_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  bool operator == (const TransferLeaderRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(leader_id == rhs.leader_id))
      return false;
    if (__isset.peer_id != rhs.__isset.peer_id)
      return false;
    else if (__isset.peer_id && !(peer_id == rhs.peer_id))
      return false;
    return true;
  }
  bool operator != (const TransferLeaderRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferLeaderRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TransferLeaderRequest &a, TransferLeaderRequest &b);

std::ostream& operator<<(std::ostream& out, const TransferLeaderRequest& obj);


/**
 * TransferLeaderResponse - Result of transfer_leader operation
 */
class TransferLeaderResponse : public virtual ::apache::thrift::TBase {
 public:

  TransferLeaderResponse(const TransferLeaderResponse&) noexcept;
  TransferLeaderResponse& operator=(const TransferLeaderResponse&) noexcept;
  TransferLeaderResponse() noexcept {
  }

  virtual ~TransferLeaderResponse() noexcept;

  bool operator == (const TransferLeaderResponse & /* rhs */) const
  {
    return true;
  }
  bool operator != (const TransferLeaderResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferLeaderResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TransferLeaderResponse &a, TransferLeaderResponse &b);

std::ostream& operator<<(std::ostream& out, const TransferLeaderResponse& obj);

typedef struct _GetLeaderRequest__isset {
  _GetLeaderRequest__isset() : group_id(false), peer_id(false) {}
  bool group_id :1;
  bool peer_id :1;
} _GetLeaderRequest__isset;

/**
 * GetLeaderRequest - Query current leader
 */
class GetLeaderRequest : public virtual ::apache::thrift::TBase {
 public:

  GetLeaderRequest(const GetLeaderRequest&);
  GetLeaderRequest& operator=(const GetLeaderRequest&);
  GetLeaderRequest() noexcept
                   : group_id(),
                     peer_id() {
  }

  virtual ~GetLeaderRequest() noexcept;
  std::string group_id;
  std::string peer_id;

  _GetLeaderRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  bool operator == (const GetLeaderRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (__isset.peer_id != rhs.__isset.peer_id)
      return false;
    else if (__isset.peer_id && !(peer_id == rhs.peer_id))
      return false;
    return true;
  }
  bool operator != (const GetLeaderRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetLeaderRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GetLeaderRequest &a, GetLeaderRequest &b);

std::ostream& operator<<(std::ostream& out, const GetLeaderRequest& obj);

typedef struct _GetLeaderResponse__isset {
  _GetLeaderResponse__isset() : leader_id(false) {}
  bool leader_id :1;
} _GetLeaderResponse__isset;

/**
 * GetLeaderResponse - Current leader information
 */
class GetLeaderResponse : public virtual ::apache::thrift::TBase {
 public:

  GetLeaderResponse(const GetLeaderResponse&);
  GetLeaderResponse& operator=(const GetLeaderResponse&);
  GetLeaderResponse() noexcept
                    : leader_id() {
  }

  virtual ~GetLeaderResponse() noexcept;
  std::string leader_id;

  _GetLeaderResponse__isset __isset;

  void __set_leader_id(const std::string& val);

  bool operator == (const GetLeaderResponse & rhs) const
  {
    if (!(leader_id == rhs.leader_id))
      return false;
    return true;
  }
  bool operator != (const GetLeaderResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetLeaderResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GetLeaderResponse &a, GetLeaderResponse &b);

std::ostream& operator<<(std::ostream& out, const GetLeaderResponse& obj);

} // namespace

#endif
