/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cli_service_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace braft {


AddPeerRequest::~AddPeerRequest() noexcept {
}


void AddPeerRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void AddPeerRequest::__set_leader_id(const std::string& val) {
  this->leader_id = val;
}

void AddPeerRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}
std::ostream& operator<<(std::ostream& out, const AddPeerRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AddPeerRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->leader_id);
          this->__isset.leader_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AddPeerRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AddPeerRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("leader_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->leader_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AddPeerRequest &a, AddPeerRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.leader_id, b.leader_id);
  swap(a.peer_id, b.peer_id);
  swap(a.__isset, b.__isset);
}

AddPeerRequest::AddPeerRequest(const AddPeerRequest& other0) {
  group_id = other0.group_id;
  leader_id = other0.leader_id;
  peer_id = other0.peer_id;
  __isset = other0.__isset;
}
AddPeerRequest& AddPeerRequest::operator=(const AddPeerRequest& other1) {
  group_id = other1.group_id;
  leader_id = other1.leader_id;
  peer_id = other1.peer_id;
  __isset = other1.__isset;
  return *this;
}
void AddPeerRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AddPeerRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "leader_id=" << to_string(leader_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ")";
}


AddPeerResponse::~AddPeerResponse() noexcept {
}


void AddPeerResponse::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}

void AddPeerResponse::__set_new_peers(const std::vector<std::string> & val) {
  this->new_peers = val;
}
std::ostream& operator<<(std::ostream& out, const AddPeerResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AddPeerResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size2;
            ::apache::thrift::protocol::TType _etype5;
            xfer += iprot->readListBegin(_etype5, _size2);
            this->old_peers.resize(_size2);
            uint32_t _i6;
            for (_i6 = 0; _i6 < _size2; ++_i6)
            {
              xfer += iprot->readString(this->old_peers[_i6]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->new_peers.clear();
            uint32_t _size7;
            ::apache::thrift::protocol::TType _etype10;
            xfer += iprot->readListBegin(_etype10, _size7);
            this->new_peers.resize(_size7);
            uint32_t _i11;
            for (_i11 = 0; _i11 < _size7; ++_i11)
            {
              xfer += iprot->readString(this->new_peers[_i11]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.new_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AddPeerResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AddPeerResponse");

  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter12;
    for (_iter12 = this->old_peers.begin(); _iter12 != this->old_peers.end(); ++_iter12)
    {
      xfer += oprot->writeString((*_iter12));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("new_peers", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->new_peers.size()));
    std::vector<std::string> ::const_iterator _iter13;
    for (_iter13 = this->new_peers.begin(); _iter13 != this->new_peers.end(); ++_iter13)
    {
      xfer += oprot->writeString((*_iter13));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AddPeerResponse &a, AddPeerResponse &b) {
  using ::std::swap;
  swap(a.old_peers, b.old_peers);
  swap(a.new_peers, b.new_peers);
  swap(a.__isset, b.__isset);
}

AddPeerResponse::AddPeerResponse(const AddPeerResponse& other14) {
  old_peers = other14.old_peers;
  new_peers = other14.new_peers;
  __isset = other14.__isset;
}
AddPeerResponse& AddPeerResponse::operator=(const AddPeerResponse& other15) {
  old_peers = other15.old_peers;
  new_peers = other15.new_peers;
  __isset = other15.__isset;
  return *this;
}
void AddPeerResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AddPeerResponse(";
  out << "old_peers=" << to_string(old_peers);
  out << ", " << "new_peers=" << to_string(new_peers);
  out << ")";
}


RemovePeerRequest::~RemovePeerRequest() noexcept {
}


void RemovePeerRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void RemovePeerRequest::__set_leader_id(const std::string& val) {
  this->leader_id = val;
}

void RemovePeerRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}
std::ostream& operator<<(std::ostream& out, const RemovePeerRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t RemovePeerRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->leader_id);
          this->__isset.leader_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RemovePeerRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("RemovePeerRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("leader_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->leader_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RemovePeerRequest &a, RemovePeerRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.leader_id, b.leader_id);
  swap(a.peer_id, b.peer_id);
  swap(a.__isset, b.__isset);
}

RemovePeerRequest::RemovePeerRequest(const RemovePeerRequest& other16) {
  group_id = other16.group_id;
  leader_id = other16.leader_id;
  peer_id = other16.peer_id;
  __isset = other16.__isset;
}
RemovePeerRequest& RemovePeerRequest::operator=(const RemovePeerRequest& other17) {
  group_id = other17.group_id;
  leader_id = other17.leader_id;
  peer_id = other17.peer_id;
  __isset = other17.__isset;
  return *this;
}
void RemovePeerRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "RemovePeerRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "leader_id=" << to_string(leader_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ")";
}


RemovePeerResponse::~RemovePeerResponse() noexcept {
}


void RemovePeerResponse::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}

void RemovePeerResponse::__set_new_peers(const std::vector<std::string> & val) {
  this->new_peers = val;
}
std::ostream& operator<<(std::ostream& out, const RemovePeerResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t RemovePeerResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size18;
            ::apache::thrift::protocol::TType _etype21;
            xfer += iprot->readListBegin(_etype21, _size18);
            this->old_peers.resize(_size18);
            uint32_t _i22;
            for (_i22 = 0; _i22 < _size18; ++_i22)
            {
              xfer += iprot->readString(this->old_peers[_i22]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->new_peers.clear();
            uint32_t _size23;
            ::apache::thrift::protocol::TType _etype26;
            xfer += iprot->readListBegin(_etype26, _size23);
            this->new_peers.resize(_size23);
            uint32_t _i27;
            for (_i27 = 0; _i27 < _size23; ++_i27)
            {
              xfer += iprot->readString(this->new_peers[_i27]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.new_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RemovePeerResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("RemovePeerResponse");

  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter28;
    for (_iter28 = this->old_peers.begin(); _iter28 != this->old_peers.end(); ++_iter28)
    {
      xfer += oprot->writeString((*_iter28));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("new_peers", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->new_peers.size()));
    std::vector<std::string> ::const_iterator _iter29;
    for (_iter29 = this->new_peers.begin(); _iter29 != this->new_peers.end(); ++_iter29)
    {
      xfer += oprot->writeString((*_iter29));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RemovePeerResponse &a, RemovePeerResponse &b) {
  using ::std::swap;
  swap(a.old_peers, b.old_peers);
  swap(a.new_peers, b.new_peers);
  swap(a.__isset, b.__isset);
}

RemovePeerResponse::RemovePeerResponse(const RemovePeerResponse& other30) {
  old_peers = other30.old_peers;
  new_peers = other30.new_peers;
  __isset = other30.__isset;
}
RemovePeerResponse& RemovePeerResponse::operator=(const RemovePeerResponse& other31) {
  old_peers = other31.old_peers;
  new_peers = other31.new_peers;
  __isset = other31.__isset;
  return *this;
}
void RemovePeerResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "RemovePeerResponse(";
  out << "old_peers=" << to_string(old_peers);
  out << ", " << "new_peers=" << to_string(new_peers);
  out << ")";
}


ChangePeersRequest::~ChangePeersRequest() noexcept {
}


void ChangePeersRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void ChangePeersRequest::__set_leader_id(const std::string& val) {
  this->leader_id = val;
}

void ChangePeersRequest::__set_new_peers(const std::vector<std::string> & val) {
  this->new_peers = val;
}
std::ostream& operator<<(std::ostream& out, const ChangePeersRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ChangePeersRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->leader_id);
          this->__isset.leader_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->new_peers.clear();
            uint32_t _size32;
            ::apache::thrift::protocol::TType _etype35;
            xfer += iprot->readListBegin(_etype35, _size32);
            this->new_peers.resize(_size32);
            uint32_t _i36;
            for (_i36 = 0; _i36 < _size32; ++_i36)
            {
              xfer += iprot->readString(this->new_peers[_i36]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.new_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ChangePeersRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ChangePeersRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("leader_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->leader_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("new_peers", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->new_peers.size()));
    std::vector<std::string> ::const_iterator _iter37;
    for (_iter37 = this->new_peers.begin(); _iter37 != this->new_peers.end(); ++_iter37)
    {
      xfer += oprot->writeString((*_iter37));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ChangePeersRequest &a, ChangePeersRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.leader_id, b.leader_id);
  swap(a.new_peers, b.new_peers);
  swap(a.__isset, b.__isset);
}

ChangePeersRequest::ChangePeersRequest(const ChangePeersRequest& other38) {
  group_id = other38.group_id;
  leader_id = other38.leader_id;
  new_peers = other38.new_peers;
  __isset = other38.__isset;
}
ChangePeersRequest& ChangePeersRequest::operator=(const ChangePeersRequest& other39) {
  group_id = other39.group_id;
  leader_id = other39.leader_id;
  new_peers = other39.new_peers;
  __isset = other39.__isset;
  return *this;
}
void ChangePeersRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ChangePeersRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "leader_id=" << to_string(leader_id);
  out << ", " << "new_peers=" << to_string(new_peers);
  out << ")";
}


ChangePeersResponse::~ChangePeersResponse() noexcept {
}


void ChangePeersResponse::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}

void ChangePeersResponse::__set_new_peers(const std::vector<std::string> & val) {
  this->new_peers = val;
}
std::ostream& operator<<(std::ostream& out, const ChangePeersResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ChangePeersResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size40;
            ::apache::thrift::protocol::TType _etype43;
            xfer += iprot->readListBegin(_etype43, _size40);
            this->old_peers.resize(_size40);
            uint32_t _i44;
            for (_i44 = 0; _i44 < _size40; ++_i44)
            {
              xfer += iprot->readString(this->old_peers[_i44]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->new_peers.clear();
            uint32_t _size45;
            ::apache::thrift::protocol::TType _etype48;
            xfer += iprot->readListBegin(_etype48, _size45);
            this->new_peers.resize(_size45);
            uint32_t _i49;
            for (_i49 = 0; _i49 < _size45; ++_i49)
            {
              xfer += iprot->readString(this->new_peers[_i49]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.new_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ChangePeersResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ChangePeersResponse");

  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter50;
    for (_iter50 = this->old_peers.begin(); _iter50 != this->old_peers.end(); ++_iter50)
    {
      xfer += oprot->writeString((*_iter50));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("new_peers", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->new_peers.size()));
    std::vector<std::string> ::const_iterator _iter51;
    for (_iter51 = this->new_peers.begin(); _iter51 != this->new_peers.end(); ++_iter51)
    {
      xfer += oprot->writeString((*_iter51));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ChangePeersResponse &a, ChangePeersResponse &b) {
  using ::std::swap;
  swap(a.old_peers, b.old_peers);
  swap(a.new_peers, b.new_peers);
  swap(a.__isset, b.__isset);
}

ChangePeersResponse::ChangePeersResponse(const ChangePeersResponse& other52) {
  old_peers = other52.old_peers;
  new_peers = other52.new_peers;
  __isset = other52.__isset;
}
ChangePeersResponse& ChangePeersResponse::operator=(const ChangePeersResponse& other53) {
  old_peers = other53.old_peers;
  new_peers = other53.new_peers;
  __isset = other53.__isset;
  return *this;
}
void ChangePeersResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ChangePeersResponse(";
  out << "old_peers=" << to_string(old_peers);
  out << ", " << "new_peers=" << to_string(new_peers);
  out << ")";
}


ResetPeerRequest::~ResetPeerRequest() noexcept {
}


void ResetPeerRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void ResetPeerRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}

void ResetPeerRequest::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}

void ResetPeerRequest::__set_new_peers(const std::vector<std::string> & val) {
  this->new_peers = val;
}
std::ostream& operator<<(std::ostream& out, const ResetPeerRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ResetPeerRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size54;
            ::apache::thrift::protocol::TType _etype57;
            xfer += iprot->readListBegin(_etype57, _size54);
            this->old_peers.resize(_size54);
            uint32_t _i58;
            for (_i58 = 0; _i58 < _size54; ++_i58)
            {
              xfer += iprot->readString(this->old_peers[_i58]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->new_peers.clear();
            uint32_t _size59;
            ::apache::thrift::protocol::TType _etype62;
            xfer += iprot->readListBegin(_etype62, _size59);
            this->new_peers.resize(_size59);
            uint32_t _i63;
            for (_i63 = 0; _i63 < _size59; ++_i63)
            {
              xfer += iprot->readString(this->new_peers[_i63]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.new_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ResetPeerRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ResetPeerRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter64;
    for (_iter64 = this->old_peers.begin(); _iter64 != this->old_peers.end(); ++_iter64)
    {
      xfer += oprot->writeString((*_iter64));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("new_peers", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->new_peers.size()));
    std::vector<std::string> ::const_iterator _iter65;
    for (_iter65 = this->new_peers.begin(); _iter65 != this->new_peers.end(); ++_iter65)
    {
      xfer += oprot->writeString((*_iter65));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ResetPeerRequest &a, ResetPeerRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.peer_id, b.peer_id);
  swap(a.old_peers, b.old_peers);
  swap(a.new_peers, b.new_peers);
  swap(a.__isset, b.__isset);
}

ResetPeerRequest::ResetPeerRequest(const ResetPeerRequest& other66) {
  group_id = other66.group_id;
  peer_id = other66.peer_id;
  old_peers = other66.old_peers;
  new_peers = other66.new_peers;
  __isset = other66.__isset;
}
ResetPeerRequest& ResetPeerRequest::operator=(const ResetPeerRequest& other67) {
  group_id = other67.group_id;
  peer_id = other67.peer_id;
  old_peers = other67.old_peers;
  new_peers = other67.new_peers;
  __isset = other67.__isset;
  return *this;
}
void ResetPeerRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ResetPeerRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ", " << "old_peers=" << to_string(old_peers);
  out << ", " << "new_peers=" << to_string(new_peers);
  out << ")";
}


ResetPeerResponse::~ResetPeerResponse() noexcept {
}

std::ostream& operator<<(std::ostream& out, const ResetPeerResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ResetPeerResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ResetPeerResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ResetPeerResponse");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ResetPeerResponse &a, ResetPeerResponse &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

ResetPeerResponse::ResetPeerResponse(const ResetPeerResponse& other68) noexcept {
  (void) other68;
}
ResetPeerResponse& ResetPeerResponse::operator=(const ResetPeerResponse& other69) noexcept {
  (void) other69;
  return *this;
}
void ResetPeerResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ResetPeerResponse(";
  out << ")";
}


SnapshotRequest::~SnapshotRequest() noexcept {
}


void SnapshotRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void SnapshotRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
__isset.peer_id = true;
}
std::ostream& operator<<(std::ostream& out, const SnapshotRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SnapshotRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SnapshotRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SnapshotRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.peer_id) {
    xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeString(this->peer_id);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SnapshotRequest &a, SnapshotRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.peer_id, b.peer_id);
  swap(a.__isset, b.__isset);
}

SnapshotRequest::SnapshotRequest(const SnapshotRequest& other70) {
  group_id = other70.group_id;
  peer_id = other70.peer_id;
  __isset = other70.__isset;
}
SnapshotRequest& SnapshotRequest::operator=(const SnapshotRequest& other71) {
  group_id = other71.group_id;
  peer_id = other71.peer_id;
  __isset = other71.__isset;
  return *this;
}
void SnapshotRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SnapshotRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "peer_id="; (__isset.peer_id ? (out << to_string(peer_id)) : (out << "<null>"));
  out << ")";
}


SnapshotResponse::~SnapshotResponse() noexcept {
}

std::ostream& operator<<(std::ostream& out, const SnapshotResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SnapshotResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SnapshotResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SnapshotResponse");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SnapshotResponse &a, SnapshotResponse &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

SnapshotResponse::SnapshotResponse(const SnapshotResponse& other72) noexcept {
  (void) other72;
}
SnapshotResponse& SnapshotResponse::operator=(const SnapshotResponse& other73) noexcept {
  (void) other73;
  return *this;
}
void SnapshotResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SnapshotResponse(";
  out << ")";
}


TransferLeaderRequest::~TransferLeaderRequest() noexcept {
}


void TransferLeaderRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void TransferLeaderRequest::__set_leader_id(const std::string& val) {
  this->leader_id = val;
}

void TransferLeaderRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
__isset.peer_id = true;
}
std::ostream& operator<<(std::ostream& out, const TransferLeaderRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TransferLeaderRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->leader_id);
          this->__isset.leader_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TransferLeaderRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TransferLeaderRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("leader_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->leader_id);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.peer_id) {
    xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->peer_id);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TransferLeaderRequest &a, TransferLeaderRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.leader_id, b.leader_id);
  swap(a.peer_id, b.peer_id);
  swap(a.__isset, b.__isset);
}

TransferLeaderRequest::TransferLeaderRequest(const TransferLeaderRequest& other74) {
  group_id = other74.group_id;
  leader_id = other74.leader_id;
  peer_id = other74.peer_id;
  __isset = other74.__isset;
}
TransferLeaderRequest& TransferLeaderRequest::operator=(const TransferLeaderRequest& other75) {
  group_id = other75.group_id;
  leader_id = other75.leader_id;
  peer_id = other75.peer_id;
  __isset = other75.__isset;
  return *this;
}
void TransferLeaderRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TransferLeaderRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "leader_id=" << to_string(leader_id);
  out << ", " << "peer_id="; (__isset.peer_id ? (out << to_string(peer_id)) : (out << "<null>"));
  out << ")";
}


TransferLeaderResponse::~TransferLeaderResponse() noexcept {
}

std::ostream& operator<<(std::ostream& out, const TransferLeaderResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TransferLeaderResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TransferLeaderResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TransferLeaderResponse");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TransferLeaderResponse &a, TransferLeaderResponse &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

TransferLeaderResponse::TransferLeaderResponse(const TransferLeaderResponse& other76) noexcept {
  (void) other76;
}
TransferLeaderResponse& TransferLeaderResponse::operator=(const TransferLeaderResponse& other77) noexcept {
  (void) other77;
  return *this;
}
void TransferLeaderResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TransferLeaderResponse(";
  out << ")";
}


GetLeaderRequest::~GetLeaderRequest() noexcept {
}


void GetLeaderRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void GetLeaderRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
__isset.peer_id = true;
}
std::ostream& operator<<(std::ostream& out, const GetLeaderRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GetLeaderRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t GetLeaderRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GetLeaderRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.peer_id) {
    xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeString(this->peer_id);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GetLeaderRequest &a, GetLeaderRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.peer_id, b.peer_id);
  swap(a.__isset, b.__isset);
}

GetLeaderRequest::GetLeaderRequest(const GetLeaderRequest& other78) {
  group_id = other78.group_id;
  peer_id = other78.peer_id;
  __isset = other78.__isset;
}
GetLeaderRequest& GetLeaderRequest::operator=(const GetLeaderRequest& other79) {
  group_id = other79.group_id;
  peer_id = other79.peer_id;
  __isset = other79.__isset;
  return *this;
}
void GetLeaderRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GetLeaderRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "peer_id="; (__isset.peer_id ? (out << to_string(peer_id)) : (out << "<null>"));
  out << ")";
}


GetLeaderResponse::~GetLeaderResponse() noexcept {
}


void GetLeaderResponse::__set_leader_id(const std::string& val) {
  this->leader_id = val;
}
std::ostream& operator<<(std::ostream& out, const GetLeaderResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GetLeaderResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->leader_id);
          this->__isset.leader_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t GetLeaderResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GetLeaderResponse");

  xfer += oprot->writeFieldBegin("leader_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->leader_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GetLeaderResponse &a, GetLeaderResponse &b) {
  using ::std::swap;
  swap(a.leader_id, b.leader_id);
  swap(a.__isset, b.__isset);
}

GetLeaderResponse::GetLeaderResponse(const GetLeaderResponse& other80) {
  leader_id = other80.leader_id;
  __isset = other80.__isset;
}
GetLeaderResponse& GetLeaderResponse::operator=(const GetLeaderResponse& other81) {
  leader_id = other81.leader_id;
  __isset = other81.__isset;
  return *this;
}
void GetLeaderResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GetLeaderResponse(";
  out << "leader_id=" << to_string(leader_id);
  out << ")";
}

} // namespace
