// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CliService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::braft;

class CliServiceHandler : virtual public CliServiceIf {
 public:
  CliServiceHandler() {
    // Your initialization goes here
  }

  /**
   * addPeer - Add a new peer to the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void addPeer(AddPeerResponse& _return, const AddPeerRequest& req) {
    // Your implementation goes here
    printf("addPeer\n");
  }

  /**
   * removePeer - Remove a peer from the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void removePeer(RemovePeerResponse& _return, const RemovePeerRequest& req) {
    // Your implementation goes here
    printf("removePeer\n");
  }

  /**
   * changePeers - Replace the entire peer configuration
   * More efficient than multiple add/remove operations
   * 
   * @param req
   */
  void changePeers(ChangePeersResponse& _return, const ChangePeersRequest& req) {
    // Your implementation goes here
    printf("changePeers\n");
  }

  /**
   * resetPeer - Force a peer to adopt a specific configuration
   * Used for recovery from split-brain scenarios
   * WARNING: Use with caution, can cause data loss
   * 
   * @param req
   */
  void resetPeer(ResetPeerResponse& _return, const ResetPeerRequest& req) {
    // Your implementation goes here
    printf("resetPeer\n");
  }

  /**
   * snapshot - Trigger snapshot creation on specified peer
   * If peer_id is empty, creates snapshot on leader
   * 
   * @param req
   */
  void snapshot(SnapshotResponse& _return, const SnapshotRequest& req) {
    // Your implementation goes here
    printf("snapshot\n");
  }

  /**
   * getLeader - Query the current leader of the group
   * Can be sent to any peer in the group
   * 
   * @param req
   */
  void getLeader(GetLeaderResponse& _return, const GetLeaderRequest& req) {
    // Your implementation goes here
    printf("getLeader\n");
  }

  /**
   * transferLeader - Transfer leadership to another peer
   * If peer_id is empty, leader selects a suitable follower
   * 
   * @param req
   */
  void transferLeader(TransferLeaderResponse& _return, const TransferLeaderRequest& req) {
    // Your implementation goes here
    printf("transferLeader\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<CliServiceHandler> handler(new CliServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new CliServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

