/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CliService_H
#define CliService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "cli_service_types.h"

namespace braft {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

/**
 * CliService - Cluster management service
 * 
 * This service provides administrative operations for Raft cluster management:
 * - Add/remove/change peers (configuration changes)
 * - Trigger snapshots
 * - Transfer leadership
 * - Query cluster state
 * 
 * All operations should be sent to the current leader, except get_leader
 * which can be sent to any peer.
 * 
 * fbthrift generates coroutine-based methods (co_*) for async operations.
 */
class CliServiceIf {
 public:
  virtual ~CliServiceIf() {}

  /**
   * addPeer - Add a new peer to the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  virtual void addPeer(AddPeerResponse& _return, const AddPeerRequest& req) = 0;

  /**
   * removePeer - Remove a peer from the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  virtual void removePeer(RemovePeerResponse& _return, const RemovePeerRequest& req) = 0;

  /**
   * changePeers - Replace the entire peer configuration
   * More efficient than multiple add/remove operations
   * 
   * @param req
   */
  virtual void changePeers(ChangePeersResponse& _return, const ChangePeersRequest& req) = 0;

  /**
   * resetPeer - Force a peer to adopt a specific configuration
   * Used for recovery from split-brain scenarios
   * WARNING: Use with caution, can cause data loss
   * 
   * @param req
   */
  virtual void resetPeer(ResetPeerResponse& _return, const ResetPeerRequest& req) = 0;

  /**
   * snapshot - Trigger snapshot creation on specified peer
   * If peer_id is empty, creates snapshot on leader
   * 
   * @param req
   */
  virtual void snapshot(SnapshotResponse& _return, const SnapshotRequest& req) = 0;

  /**
   * getLeader - Query the current leader of the group
   * Can be sent to any peer in the group
   * 
   * @param req
   */
  virtual void getLeader(GetLeaderResponse& _return, const GetLeaderRequest& req) = 0;

  /**
   * transferLeader - Transfer leadership to another peer
   * If peer_id is empty, leader selects a suitable follower
   * 
   * @param req
   */
  virtual void transferLeader(TransferLeaderResponse& _return, const TransferLeaderRequest& req) = 0;
};

class CliServiceIfFactory {
 public:
  typedef CliServiceIf Handler;

  virtual ~CliServiceIfFactory() {}

  virtual CliServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CliServiceIf* /* handler */) = 0;
  };

class CliServiceIfSingletonFactory : virtual public CliServiceIfFactory {
 public:
  CliServiceIfSingletonFactory(const ::std::shared_ptr<CliServiceIf>& iface) : iface_(iface) {}
  virtual ~CliServiceIfSingletonFactory() {}

  virtual CliServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(CliServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<CliServiceIf> iface_;
};

class CliServiceNull : virtual public CliServiceIf {
 public:
  virtual ~CliServiceNull() {}
  void addPeer(AddPeerResponse& /* _return */, const AddPeerRequest& /* req */) override {
    return;
  }
  void removePeer(RemovePeerResponse& /* _return */, const RemovePeerRequest& /* req */) override {
    return;
  }
  void changePeers(ChangePeersResponse& /* _return */, const ChangePeersRequest& /* req */) override {
    return;
  }
  void resetPeer(ResetPeerResponse& /* _return */, const ResetPeerRequest& /* req */) override {
    return;
  }
  void snapshot(SnapshotResponse& /* _return */, const SnapshotRequest& /* req */) override {
    return;
  }
  void getLeader(GetLeaderResponse& /* _return */, const GetLeaderRequest& /* req */) override {
    return;
  }
  void transferLeader(TransferLeaderResponse& /* _return */, const TransferLeaderRequest& /* req */) override {
    return;
  }
};

typedef struct _CliService_addPeer_args__isset {
  _CliService_addPeer_args__isset() : req(false) {}
  bool req :1;
} _CliService_addPeer_args__isset;

class CliService_addPeer_args {
 public:

  CliService_addPeer_args(const CliService_addPeer_args&);
  CliService_addPeer_args& operator=(const CliService_addPeer_args&);
  CliService_addPeer_args() noexcept {
  }

  virtual ~CliService_addPeer_args() noexcept;
  AddPeerRequest req;

  _CliService_addPeer_args__isset __isset;

  void __set_req(const AddPeerRequest& val);

  bool operator == (const CliService_addPeer_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_addPeer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_addPeer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_addPeer_pargs {
 public:


  virtual ~CliService_addPeer_pargs() noexcept;
  const AddPeerRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_addPeer_result__isset {
  _CliService_addPeer_result__isset() : success(false) {}
  bool success :1;
} _CliService_addPeer_result__isset;

class CliService_addPeer_result {
 public:

  CliService_addPeer_result(const CliService_addPeer_result&);
  CliService_addPeer_result& operator=(const CliService_addPeer_result&);
  CliService_addPeer_result() noexcept {
  }

  virtual ~CliService_addPeer_result() noexcept;
  AddPeerResponse success;

  _CliService_addPeer_result__isset __isset;

  void __set_success(const AddPeerResponse& val);

  bool operator == (const CliService_addPeer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_addPeer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_addPeer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_addPeer_presult__isset {
  _CliService_addPeer_presult__isset() : success(false) {}
  bool success :1;
} _CliService_addPeer_presult__isset;

class CliService_addPeer_presult {
 public:


  virtual ~CliService_addPeer_presult() noexcept;
  AddPeerResponse* success;

  _CliService_addPeer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CliService_removePeer_args__isset {
  _CliService_removePeer_args__isset() : req(false) {}
  bool req :1;
} _CliService_removePeer_args__isset;

class CliService_removePeer_args {
 public:

  CliService_removePeer_args(const CliService_removePeer_args&);
  CliService_removePeer_args& operator=(const CliService_removePeer_args&);
  CliService_removePeer_args() noexcept {
  }

  virtual ~CliService_removePeer_args() noexcept;
  RemovePeerRequest req;

  _CliService_removePeer_args__isset __isset;

  void __set_req(const RemovePeerRequest& val);

  bool operator == (const CliService_removePeer_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_removePeer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_removePeer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_removePeer_pargs {
 public:


  virtual ~CliService_removePeer_pargs() noexcept;
  const RemovePeerRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_removePeer_result__isset {
  _CliService_removePeer_result__isset() : success(false) {}
  bool success :1;
} _CliService_removePeer_result__isset;

class CliService_removePeer_result {
 public:

  CliService_removePeer_result(const CliService_removePeer_result&);
  CliService_removePeer_result& operator=(const CliService_removePeer_result&);
  CliService_removePeer_result() noexcept {
  }

  virtual ~CliService_removePeer_result() noexcept;
  RemovePeerResponse success;

  _CliService_removePeer_result__isset __isset;

  void __set_success(const RemovePeerResponse& val);

  bool operator == (const CliService_removePeer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_removePeer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_removePeer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_removePeer_presult__isset {
  _CliService_removePeer_presult__isset() : success(false) {}
  bool success :1;
} _CliService_removePeer_presult__isset;

class CliService_removePeer_presult {
 public:


  virtual ~CliService_removePeer_presult() noexcept;
  RemovePeerResponse* success;

  _CliService_removePeer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CliService_changePeers_args__isset {
  _CliService_changePeers_args__isset() : req(false) {}
  bool req :1;
} _CliService_changePeers_args__isset;

class CliService_changePeers_args {
 public:

  CliService_changePeers_args(const CliService_changePeers_args&);
  CliService_changePeers_args& operator=(const CliService_changePeers_args&);
  CliService_changePeers_args() noexcept {
  }

  virtual ~CliService_changePeers_args() noexcept;
  ChangePeersRequest req;

  _CliService_changePeers_args__isset __isset;

  void __set_req(const ChangePeersRequest& val);

  bool operator == (const CliService_changePeers_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_changePeers_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_changePeers_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_changePeers_pargs {
 public:


  virtual ~CliService_changePeers_pargs() noexcept;
  const ChangePeersRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_changePeers_result__isset {
  _CliService_changePeers_result__isset() : success(false) {}
  bool success :1;
} _CliService_changePeers_result__isset;

class CliService_changePeers_result {
 public:

  CliService_changePeers_result(const CliService_changePeers_result&);
  CliService_changePeers_result& operator=(const CliService_changePeers_result&);
  CliService_changePeers_result() noexcept {
  }

  virtual ~CliService_changePeers_result() noexcept;
  ChangePeersResponse success;

  _CliService_changePeers_result__isset __isset;

  void __set_success(const ChangePeersResponse& val);

  bool operator == (const CliService_changePeers_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_changePeers_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_changePeers_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_changePeers_presult__isset {
  _CliService_changePeers_presult__isset() : success(false) {}
  bool success :1;
} _CliService_changePeers_presult__isset;

class CliService_changePeers_presult {
 public:


  virtual ~CliService_changePeers_presult() noexcept;
  ChangePeersResponse* success;

  _CliService_changePeers_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CliService_resetPeer_args__isset {
  _CliService_resetPeer_args__isset() : req(false) {}
  bool req :1;
} _CliService_resetPeer_args__isset;

class CliService_resetPeer_args {
 public:

  CliService_resetPeer_args(const CliService_resetPeer_args&);
  CliService_resetPeer_args& operator=(const CliService_resetPeer_args&);
  CliService_resetPeer_args() noexcept {
  }

  virtual ~CliService_resetPeer_args() noexcept;
  ResetPeerRequest req;

  _CliService_resetPeer_args__isset __isset;

  void __set_req(const ResetPeerRequest& val);

  bool operator == (const CliService_resetPeer_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_resetPeer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_resetPeer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_resetPeer_pargs {
 public:


  virtual ~CliService_resetPeer_pargs() noexcept;
  const ResetPeerRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_resetPeer_result__isset {
  _CliService_resetPeer_result__isset() : success(false) {}
  bool success :1;
} _CliService_resetPeer_result__isset;

class CliService_resetPeer_result {
 public:

  CliService_resetPeer_result(const CliService_resetPeer_result&) noexcept;
  CliService_resetPeer_result& operator=(const CliService_resetPeer_result&) noexcept;
  CliService_resetPeer_result() noexcept {
  }

  virtual ~CliService_resetPeer_result() noexcept;
  ResetPeerResponse success;

  _CliService_resetPeer_result__isset __isset;

  void __set_success(const ResetPeerResponse& val);

  bool operator == (const CliService_resetPeer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_resetPeer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_resetPeer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_resetPeer_presult__isset {
  _CliService_resetPeer_presult__isset() : success(false) {}
  bool success :1;
} _CliService_resetPeer_presult__isset;

class CliService_resetPeer_presult {
 public:


  virtual ~CliService_resetPeer_presult() noexcept;
  ResetPeerResponse* success;

  _CliService_resetPeer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CliService_snapshot_args__isset {
  _CliService_snapshot_args__isset() : req(false) {}
  bool req :1;
} _CliService_snapshot_args__isset;

class CliService_snapshot_args {
 public:

  CliService_snapshot_args(const CliService_snapshot_args&);
  CliService_snapshot_args& operator=(const CliService_snapshot_args&);
  CliService_snapshot_args() noexcept {
  }

  virtual ~CliService_snapshot_args() noexcept;
  SnapshotRequest req;

  _CliService_snapshot_args__isset __isset;

  void __set_req(const SnapshotRequest& val);

  bool operator == (const CliService_snapshot_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_snapshot_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_snapshot_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_snapshot_pargs {
 public:


  virtual ~CliService_snapshot_pargs() noexcept;
  const SnapshotRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_snapshot_result__isset {
  _CliService_snapshot_result__isset() : success(false) {}
  bool success :1;
} _CliService_snapshot_result__isset;

class CliService_snapshot_result {
 public:

  CliService_snapshot_result(const CliService_snapshot_result&) noexcept;
  CliService_snapshot_result& operator=(const CliService_snapshot_result&) noexcept;
  CliService_snapshot_result() noexcept {
  }

  virtual ~CliService_snapshot_result() noexcept;
  SnapshotResponse success;

  _CliService_snapshot_result__isset __isset;

  void __set_success(const SnapshotResponse& val);

  bool operator == (const CliService_snapshot_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_snapshot_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_snapshot_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_snapshot_presult__isset {
  _CliService_snapshot_presult__isset() : success(false) {}
  bool success :1;
} _CliService_snapshot_presult__isset;

class CliService_snapshot_presult {
 public:


  virtual ~CliService_snapshot_presult() noexcept;
  SnapshotResponse* success;

  _CliService_snapshot_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CliService_getLeader_args__isset {
  _CliService_getLeader_args__isset() : req(false) {}
  bool req :1;
} _CliService_getLeader_args__isset;

class CliService_getLeader_args {
 public:

  CliService_getLeader_args(const CliService_getLeader_args&);
  CliService_getLeader_args& operator=(const CliService_getLeader_args&);
  CliService_getLeader_args() noexcept {
  }

  virtual ~CliService_getLeader_args() noexcept;
  GetLeaderRequest req;

  _CliService_getLeader_args__isset __isset;

  void __set_req(const GetLeaderRequest& val);

  bool operator == (const CliService_getLeader_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_getLeader_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_getLeader_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_getLeader_pargs {
 public:


  virtual ~CliService_getLeader_pargs() noexcept;
  const GetLeaderRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_getLeader_result__isset {
  _CliService_getLeader_result__isset() : success(false) {}
  bool success :1;
} _CliService_getLeader_result__isset;

class CliService_getLeader_result {
 public:

  CliService_getLeader_result(const CliService_getLeader_result&);
  CliService_getLeader_result& operator=(const CliService_getLeader_result&);
  CliService_getLeader_result() noexcept {
  }

  virtual ~CliService_getLeader_result() noexcept;
  GetLeaderResponse success;

  _CliService_getLeader_result__isset __isset;

  void __set_success(const GetLeaderResponse& val);

  bool operator == (const CliService_getLeader_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_getLeader_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_getLeader_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_getLeader_presult__isset {
  _CliService_getLeader_presult__isset() : success(false) {}
  bool success :1;
} _CliService_getLeader_presult__isset;

class CliService_getLeader_presult {
 public:


  virtual ~CliService_getLeader_presult() noexcept;
  GetLeaderResponse* success;

  _CliService_getLeader_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CliService_transferLeader_args__isset {
  _CliService_transferLeader_args__isset() : req(false) {}
  bool req :1;
} _CliService_transferLeader_args__isset;

class CliService_transferLeader_args {
 public:

  CliService_transferLeader_args(const CliService_transferLeader_args&);
  CliService_transferLeader_args& operator=(const CliService_transferLeader_args&);
  CliService_transferLeader_args() noexcept {
  }

  virtual ~CliService_transferLeader_args() noexcept;
  TransferLeaderRequest req;

  _CliService_transferLeader_args__isset __isset;

  void __set_req(const TransferLeaderRequest& val);

  bool operator == (const CliService_transferLeader_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const CliService_transferLeader_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_transferLeader_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CliService_transferLeader_pargs {
 public:


  virtual ~CliService_transferLeader_pargs() noexcept;
  const TransferLeaderRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_transferLeader_result__isset {
  _CliService_transferLeader_result__isset() : success(false) {}
  bool success :1;
} _CliService_transferLeader_result__isset;

class CliService_transferLeader_result {
 public:

  CliService_transferLeader_result(const CliService_transferLeader_result&) noexcept;
  CliService_transferLeader_result& operator=(const CliService_transferLeader_result&) noexcept;
  CliService_transferLeader_result() noexcept {
  }

  virtual ~CliService_transferLeader_result() noexcept;
  TransferLeaderResponse success;

  _CliService_transferLeader_result__isset __isset;

  void __set_success(const TransferLeaderResponse& val);

  bool operator == (const CliService_transferLeader_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CliService_transferLeader_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CliService_transferLeader_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CliService_transferLeader_presult__isset {
  _CliService_transferLeader_presult__isset() : success(false) {}
  bool success :1;
} _CliService_transferLeader_presult__isset;

class CliService_transferLeader_presult {
 public:


  virtual ~CliService_transferLeader_presult() noexcept;
  TransferLeaderResponse* success;

  _CliService_transferLeader_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CliServiceClient : virtual public CliServiceIf {
 public:
  CliServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CliServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * addPeer - Add a new peer to the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void addPeer(AddPeerResponse& _return, const AddPeerRequest& req) override;
  void send_addPeer(const AddPeerRequest& req);
  void recv_addPeer(AddPeerResponse& _return);
  /**
   * removePeer - Remove a peer from the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void removePeer(RemovePeerResponse& _return, const RemovePeerRequest& req) override;
  void send_removePeer(const RemovePeerRequest& req);
  void recv_removePeer(RemovePeerResponse& _return);
  /**
   * changePeers - Replace the entire peer configuration
   * More efficient than multiple add/remove operations
   * 
   * @param req
   */
  void changePeers(ChangePeersResponse& _return, const ChangePeersRequest& req) override;
  void send_changePeers(const ChangePeersRequest& req);
  void recv_changePeers(ChangePeersResponse& _return);
  /**
   * resetPeer - Force a peer to adopt a specific configuration
   * Used for recovery from split-brain scenarios
   * WARNING: Use with caution, can cause data loss
   * 
   * @param req
   */
  void resetPeer(ResetPeerResponse& _return, const ResetPeerRequest& req) override;
  void send_resetPeer(const ResetPeerRequest& req);
  void recv_resetPeer(ResetPeerResponse& _return);
  /**
   * snapshot - Trigger snapshot creation on specified peer
   * If peer_id is empty, creates snapshot on leader
   * 
   * @param req
   */
  void snapshot(SnapshotResponse& _return, const SnapshotRequest& req) override;
  void send_snapshot(const SnapshotRequest& req);
  void recv_snapshot(SnapshotResponse& _return);
  /**
   * getLeader - Query the current leader of the group
   * Can be sent to any peer in the group
   * 
   * @param req
   */
  void getLeader(GetLeaderResponse& _return, const GetLeaderRequest& req) override;
  void send_getLeader(const GetLeaderRequest& req);
  void recv_getLeader(GetLeaderResponse& _return);
  /**
   * transferLeader - Transfer leadership to another peer
   * If peer_id is empty, leader selects a suitable follower
   * 
   * @param req
   */
  void transferLeader(TransferLeaderResponse& _return, const TransferLeaderRequest& req) override;
  void send_transferLeader(const TransferLeaderRequest& req);
  void recv_transferLeader(TransferLeaderResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CliServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<CliServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (CliServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_addPeer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_removePeer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_changePeers(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_resetPeer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_snapshot(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getLeader(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_transferLeader(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CliServiceProcessor(::std::shared_ptr<CliServiceIf> iface) :
    iface_(iface) {
    processMap_["addPeer"] = &CliServiceProcessor::process_addPeer;
    processMap_["removePeer"] = &CliServiceProcessor::process_removePeer;
    processMap_["changePeers"] = &CliServiceProcessor::process_changePeers;
    processMap_["resetPeer"] = &CliServiceProcessor::process_resetPeer;
    processMap_["snapshot"] = &CliServiceProcessor::process_snapshot;
    processMap_["getLeader"] = &CliServiceProcessor::process_getLeader;
    processMap_["transferLeader"] = &CliServiceProcessor::process_transferLeader;
  }

  virtual ~CliServiceProcessor() {}
};

class CliServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CliServiceProcessorFactory(const ::std::shared_ptr< CliServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< CliServiceIfFactory > handlerFactory_;
};

class CliServiceMultiface : virtual public CliServiceIf {
 public:
  CliServiceMultiface(std::vector<std::shared_ptr<CliServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CliServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<CliServiceIf> > ifaces_;
  CliServiceMultiface() {}
  void add(::std::shared_ptr<CliServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * addPeer - Add a new peer to the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void addPeer(AddPeerResponse& _return, const AddPeerRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->addPeer(_return, req);
    }
    ifaces_[i]->addPeer(_return, req);
    return;
  }

  /**
   * removePeer - Remove a peer from the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void removePeer(RemovePeerResponse& _return, const RemovePeerRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->removePeer(_return, req);
    }
    ifaces_[i]->removePeer(_return, req);
    return;
  }

  /**
   * changePeers - Replace the entire peer configuration
   * More efficient than multiple add/remove operations
   * 
   * @param req
   */
  void changePeers(ChangePeersResponse& _return, const ChangePeersRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->changePeers(_return, req);
    }
    ifaces_[i]->changePeers(_return, req);
    return;
  }

  /**
   * resetPeer - Force a peer to adopt a specific configuration
   * Used for recovery from split-brain scenarios
   * WARNING: Use with caution, can cause data loss
   * 
   * @param req
   */
  void resetPeer(ResetPeerResponse& _return, const ResetPeerRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->resetPeer(_return, req);
    }
    ifaces_[i]->resetPeer(_return, req);
    return;
  }

  /**
   * snapshot - Trigger snapshot creation on specified peer
   * If peer_id is empty, creates snapshot on leader
   * 
   * @param req
   */
  void snapshot(SnapshotResponse& _return, const SnapshotRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->snapshot(_return, req);
    }
    ifaces_[i]->snapshot(_return, req);
    return;
  }

  /**
   * getLeader - Query the current leader of the group
   * Can be sent to any peer in the group
   * 
   * @param req
   */
  void getLeader(GetLeaderResponse& _return, const GetLeaderRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getLeader(_return, req);
    }
    ifaces_[i]->getLeader(_return, req);
    return;
  }

  /**
   * transferLeader - Transfer leadership to another peer
   * If peer_id is empty, leader selects a suitable follower
   * 
   * @param req
   */
  void transferLeader(TransferLeaderResponse& _return, const TransferLeaderRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->transferLeader(_return, req);
    }
    ifaces_[i]->transferLeader(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CliServiceConcurrentClient : virtual public CliServiceIf {
 public:
  CliServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  CliServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * addPeer - Add a new peer to the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void addPeer(AddPeerResponse& _return, const AddPeerRequest& req) override;
  int32_t send_addPeer(const AddPeerRequest& req);
  void recv_addPeer(AddPeerResponse& _return, const int32_t seqid);
  /**
   * removePeer - Remove a peer from the cluster
   * Initiates a joint consensus configuration change
   * 
   * @param req
   */
  void removePeer(RemovePeerResponse& _return, const RemovePeerRequest& req) override;
  int32_t send_removePeer(const RemovePeerRequest& req);
  void recv_removePeer(RemovePeerResponse& _return, const int32_t seqid);
  /**
   * changePeers - Replace the entire peer configuration
   * More efficient than multiple add/remove operations
   * 
   * @param req
   */
  void changePeers(ChangePeersResponse& _return, const ChangePeersRequest& req) override;
  int32_t send_changePeers(const ChangePeersRequest& req);
  void recv_changePeers(ChangePeersResponse& _return, const int32_t seqid);
  /**
   * resetPeer - Force a peer to adopt a specific configuration
   * Used for recovery from split-brain scenarios
   * WARNING: Use with caution, can cause data loss
   * 
   * @param req
   */
  void resetPeer(ResetPeerResponse& _return, const ResetPeerRequest& req) override;
  int32_t send_resetPeer(const ResetPeerRequest& req);
  void recv_resetPeer(ResetPeerResponse& _return, const int32_t seqid);
  /**
   * snapshot - Trigger snapshot creation on specified peer
   * If peer_id is empty, creates snapshot on leader
   * 
   * @param req
   */
  void snapshot(SnapshotResponse& _return, const SnapshotRequest& req) override;
  int32_t send_snapshot(const SnapshotRequest& req);
  void recv_snapshot(SnapshotResponse& _return, const int32_t seqid);
  /**
   * getLeader - Query the current leader of the group
   * Can be sent to any peer in the group
   * 
   * @param req
   */
  void getLeader(GetLeaderResponse& _return, const GetLeaderRequest& req) override;
  int32_t send_getLeader(const GetLeaderRequest& req);
  void recv_getLeader(GetLeaderResponse& _return, const int32_t seqid);
  /**
   * transferLeader - Transfer leadership to another peer
   * If peer_id is empty, leader selects a suitable follower
   * 
   * @param req
   */
  void transferLeader(TransferLeaderResponse& _return, const TransferLeaderRequest& req) override;
  int32_t send_transferLeader(const TransferLeaderRequest& req);
  void recv_transferLeader(TransferLeaderResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
