/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file_service_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace braft {


GetFileRequest::~GetFileRequest() noexcept {
}


void GetFileRequest::__set_reader_id(const int64_t val) {
  this->reader_id = val;
}

void GetFileRequest::__set_filename(const std::string& val) {
  this->filename = val;
}

void GetFileRequest::__set_count(const int64_t val) {
  this->count = val;
}

void GetFileRequest::__set_offset(const int64_t val) {
  this->offset = val;
}

void GetFileRequest::__set_read_partly(const bool val) {
  this->read_partly = val;
__isset.read_partly = true;
}
std::ostream& operator<<(std::ostream& out, const GetFileRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GetFileRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->reader_id);
          this->__isset.reader_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->filename);
          this->__isset.filename = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->count);
          this->__isset.count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->offset);
          this->__isset.offset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->read_partly);
          this->__isset.read_partly = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t GetFileRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GetFileRequest");

  xfer += oprot->writeFieldBegin("reader_id", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->reader_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("filename", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->filename);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("count", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("offset", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->offset);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.read_partly) {
    xfer += oprot->writeFieldBegin("read_partly", ::apache::thrift::protocol::T_BOOL, 5);
    xfer += oprot->writeBool(this->read_partly);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GetFileRequest &a, GetFileRequest &b) {
  using ::std::swap;
  swap(a.reader_id, b.reader_id);
  swap(a.filename, b.filename);
  swap(a.count, b.count);
  swap(a.offset, b.offset);
  swap(a.read_partly, b.read_partly);
  swap(a.__isset, b.__isset);
}

GetFileRequest::GetFileRequest(const GetFileRequest& other0) {
  reader_id = other0.reader_id;
  filename = other0.filename;
  count = other0.count;
  offset = other0.offset;
  read_partly = other0.read_partly;
  __isset = other0.__isset;
}
GetFileRequest& GetFileRequest::operator=(const GetFileRequest& other1) {
  reader_id = other1.reader_id;
  filename = other1.filename;
  count = other1.count;
  offset = other1.offset;
  read_partly = other1.read_partly;
  __isset = other1.__isset;
  return *this;
}
void GetFileRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GetFileRequest(";
  out << "reader_id=" << to_string(reader_id);
  out << ", " << "filename=" << to_string(filename);
  out << ", " << "count=" << to_string(count);
  out << ", " << "offset=" << to_string(offset);
  out << ", " << "read_partly="; (__isset.read_partly ? (out << to_string(read_partly)) : (out << "<null>"));
  out << ")";
}


GetFileResponse::~GetFileResponse() noexcept {
}


void GetFileResponse::__set_eof(const bool val) {
  this->eof = val;
}

void GetFileResponse::__set_read_size(const int64_t val) {
  this->read_size = val;
__isset.read_size = true;
}
std::ostream& operator<<(std::ostream& out, const GetFileResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GetFileResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->eof);
          this->__isset.eof = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->read_size);
          this->__isset.read_size = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t GetFileResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GetFileResponse");

  xfer += oprot->writeFieldBegin("eof", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->eof);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.read_size) {
    xfer += oprot->writeFieldBegin("read_size", ::apache::thrift::protocol::T_I64, 2);
    xfer += oprot->writeI64(this->read_size);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GetFileResponse &a, GetFileResponse &b) {
  using ::std::swap;
  swap(a.eof, b.eof);
  swap(a.read_size, b.read_size);
  swap(a.__isset, b.__isset);
}

GetFileResponse::GetFileResponse(const GetFileResponse& other2) noexcept {
  eof = other2.eof;
  read_size = other2.read_size;
  __isset = other2.__isset;
}
GetFileResponse& GetFileResponse::operator=(const GetFileResponse& other3) noexcept {
  eof = other3.eof;
  read_size = other3.read_size;
  __isset = other3.__isset;
  return *this;
}
void GetFileResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GetFileResponse(";
  out << "eof=" << to_string(eof);
  out << ", " << "read_size="; (__isset.read_size ? (out << to_string(read_size)) : (out << "<null>"));
  out << ")";
}

} // namespace
