/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef file_service_TYPES_H
#define file_service_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace braft {

class GetFileRequest;

class GetFileResponse;

typedef struct _GetFileRequest__isset {
  _GetFileRequest__isset() : reader_id(false), filename(false), count(false), offset(false), read_partly(false) {}
  bool reader_id :1;
  bool filename :1;
  bool count :1;
  bool offset :1;
  bool read_partly :1;
} _GetFileRequest__isset;

/**
 * GetFileRequest - Request to read a file chunk
 * Used for snapshot file transfer
 */
class GetFileRequest : public virtual ::apache::thrift::TBase {
 public:

  GetFileRequest(const GetFileRequest&);
  GetFileRequest& operator=(const GetFileRequest&);
  GetFileRequest() noexcept
                 : reader_id(0),
                   filename(),
                   count(0),
                   offset(0),
                   read_partly(0) {
  }

  virtual ~GetFileRequest() noexcept;
  int64_t reader_id;
  std::string filename;
  int64_t count;
  int64_t offset;
  bool read_partly;

  _GetFileRequest__isset __isset;

  void __set_reader_id(const int64_t val);

  void __set_filename(const std::string& val);

  void __set_count(const int64_t val);

  void __set_offset(const int64_t val);

  void __set_read_partly(const bool val);

  bool operator == (const GetFileRequest & rhs) const
  {
    if (!(reader_id == rhs.reader_id))
      return false;
    if (!(filename == rhs.filename))
      return false;
    if (!(count == rhs.count))
      return false;
    if (!(offset == rhs.offset))
      return false;
    if (__isset.read_partly != rhs.__isset.read_partly)
      return false;
    else if (__isset.read_partly && !(read_partly == rhs.read_partly))
      return false;
    return true;
  }
  bool operator != (const GetFileRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetFileRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GetFileRequest &a, GetFileRequest &b);

std::ostream& operator<<(std::ostream& out, const GetFileRequest& obj);

typedef struct _GetFileResponse__isset {
  _GetFileResponse__isset() : eof(false), read_size(false) {}
  bool eof :1;
  bool read_size :1;
} _GetFileResponse__isset;

/**
 * GetFileResponse - Response with file chunk data
 * Actual file data is transported in attachment for efficiency
 */
class GetFileResponse : public virtual ::apache::thrift::TBase {
 public:

  GetFileResponse(const GetFileResponse&) noexcept;
  GetFileResponse& operator=(const GetFileResponse&) noexcept;
  GetFileResponse() noexcept
                  : eof(0),
                    read_size(0) {
  }

  virtual ~GetFileResponse() noexcept;
  bool eof;
  int64_t read_size;

  _GetFileResponse__isset __isset;

  void __set_eof(const bool val);

  void __set_read_size(const int64_t val);

  bool operator == (const GetFileResponse & rhs) const
  {
    if (!(eof == rhs.eof))
      return false;
    if (__isset.read_size != rhs.__isset.read_size)
      return false;
    else if (__isset.read_size && !(read_size == rhs.read_size))
      return false;
    return true;
  }
  bool operator != (const GetFileResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetFileResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GetFileResponse &a, GetFileResponse &b);

std::ostream& operator<<(std::ostream& out, const GetFileResponse& obj);

} // namespace

#endif
