// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FileService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::braft;

class FileServiceHandler : virtual public FileServiceIf {
 public:
  FileServiceHandler() {
    // Your initialization goes here
  }

  /**
   * getFile - Read a chunk of file data
   * File data is returned in attachment
   * 
   * @param req
   */
  void getFile(GetFileResponse& _return, const GetFileRequest& req) {
    // Your implementation goes here
    printf("getFile\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<FileServiceHandler> handler(new FileServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new FileServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

