/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FileService_H
#define FileService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "file_service_types.h"

namespace braft {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

/**
 * FileService - File transfer service for snapshot copying
 * 
 * This service handles streaming file transfers from snapshot reader to
 * remote copier. The actual file data is transported via fbthrift's
 * attachment mechanism, not in the response structure.
 * 
 * For streaming support, fbthrift can use the `stream` keyword in future
 * iterations to enable true bidirectional streaming.
 * 
 * Usage flow:
 * 1. Snapshot copier requests a file with offset and count
 * 2. Snapshot reader sends back chunk data in attachment
 * 3. Repeat until eof is true
 */
class FileServiceIf {
 public:
  virtual ~FileServiceIf() {}

  /**
   * getFile - Read a chunk of file data
   * File data is returned in attachment
   * 
   * @param req
   */
  virtual void getFile(GetFileResponse& _return, const GetFileRequest& req) = 0;
};

class FileServiceIfFactory {
 public:
  typedef FileServiceIf Handler;

  virtual ~FileServiceIfFactory() {}

  virtual FileServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(FileServiceIf* /* handler */) = 0;
  };

class FileServiceIfSingletonFactory : virtual public FileServiceIfFactory {
 public:
  FileServiceIfSingletonFactory(const ::std::shared_ptr<FileServiceIf>& iface) : iface_(iface) {}
  virtual ~FileServiceIfSingletonFactory() {}

  virtual FileServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(FileServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<FileServiceIf> iface_;
};

class FileServiceNull : virtual public FileServiceIf {
 public:
  virtual ~FileServiceNull() {}
  void getFile(GetFileResponse& /* _return */, const GetFileRequest& /* req */) override {
    return;
  }
};

typedef struct _FileService_getFile_args__isset {
  _FileService_getFile_args__isset() : req(false) {}
  bool req :1;
} _FileService_getFile_args__isset;

class FileService_getFile_args {
 public:

  FileService_getFile_args(const FileService_getFile_args&);
  FileService_getFile_args& operator=(const FileService_getFile_args&);
  FileService_getFile_args() noexcept {
  }

  virtual ~FileService_getFile_args() noexcept;
  GetFileRequest req;

  _FileService_getFile_args__isset __isset;

  void __set_req(const GetFileRequest& val);

  bool operator == (const FileService_getFile_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const FileService_getFile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileService_getFile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class FileService_getFile_pargs {
 public:


  virtual ~FileService_getFile_pargs() noexcept;
  const GetFileRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _FileService_getFile_result__isset {
  _FileService_getFile_result__isset() : success(false) {}
  bool success :1;
} _FileService_getFile_result__isset;

class FileService_getFile_result {
 public:

  FileService_getFile_result(const FileService_getFile_result&) noexcept;
  FileService_getFile_result& operator=(const FileService_getFile_result&) noexcept;
  FileService_getFile_result() noexcept {
  }

  virtual ~FileService_getFile_result() noexcept;
  GetFileResponse success;

  _FileService_getFile_result__isset __isset;

  void __set_success(const GetFileResponse& val);

  bool operator == (const FileService_getFile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const FileService_getFile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileService_getFile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _FileService_getFile_presult__isset {
  _FileService_getFile_presult__isset() : success(false) {}
  bool success :1;
} _FileService_getFile_presult__isset;

class FileService_getFile_presult {
 public:


  virtual ~FileService_getFile_presult() noexcept;
  GetFileResponse* success;

  _FileService_getFile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class FileServiceClient : virtual public FileServiceIf {
 public:
  FileServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  FileServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * getFile - Read a chunk of file data
   * File data is returned in attachment
   * 
   * @param req
   */
  void getFile(GetFileResponse& _return, const GetFileRequest& req) override;
  void send_getFile(const GetFileRequest& req);
  void recv_getFile(GetFileResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class FileServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<FileServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (FileServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getFile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  FileServiceProcessor(::std::shared_ptr<FileServiceIf> iface) :
    iface_(iface) {
    processMap_["getFile"] = &FileServiceProcessor::process_getFile;
  }

  virtual ~FileServiceProcessor() {}
};

class FileServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  FileServiceProcessorFactory(const ::std::shared_ptr< FileServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< FileServiceIfFactory > handlerFactory_;
};

class FileServiceMultiface : virtual public FileServiceIf {
 public:
  FileServiceMultiface(std::vector<std::shared_ptr<FileServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~FileServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<FileServiceIf> > ifaces_;
  FileServiceMultiface() {}
  void add(::std::shared_ptr<FileServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * getFile - Read a chunk of file data
   * File data is returned in attachment
   * 
   * @param req
   */
  void getFile(GetFileResponse& _return, const GetFileRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getFile(_return, req);
    }
    ifaces_[i]->getFile(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class FileServiceConcurrentClient : virtual public FileServiceIf {
 public:
  FileServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  FileServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * getFile - Read a chunk of file data
   * File data is returned in attachment
   * 
   * @param req
   */
  void getFile(GetFileResponse& _return, const GetFileRequest& req) override;
  int32_t send_getFile(const GetFileRequest& req);
  void recv_getFile(GetFileResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
