/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef raft_TYPES_H
#define raft_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "base_types.h"


namespace braft {

class RequestVoteRequest;

class RequestVoteResponse;

class AppendEntriesRequest;

class AppendEntriesResponse;

class InstallSnapshotRequest;

class InstallSnapshotResponse;

class TimeoutNowRequest;

class TimeoutNowResponse;

typedef struct _RequestVoteRequest__isset {
  _RequestVoteRequest__isset() : group_id(false), server_id(false), peer_id(false), term(false), last_log_term(false), last_log_index(false), disrupted_leader(false) {}
  bool group_id :1;
  bool server_id :1;
  bool peer_id :1;
  bool term :1;
  bool last_log_term :1;
  bool last_log_index :1;
  bool disrupted_leader :1;
} _RequestVoteRequest__isset;

/**
 * RequestVoteRequest - RequestVote RPC parameters
 * Used for both pre-vote and actual vote phases
 */
class RequestVoteRequest : public virtual ::apache::thrift::TBase {
 public:

  RequestVoteRequest(const RequestVoteRequest&);
  RequestVoteRequest& operator=(const RequestVoteRequest&);
  RequestVoteRequest() noexcept
                     : group_id(),
                       server_id(),
                       peer_id(),
                       term(0),
                       last_log_term(0),
                       last_log_index(0) {
  }

  virtual ~RequestVoteRequest() noexcept;
  std::string group_id;
  std::string server_id;
  std::string peer_id;
  int64_t term;
  int64_t last_log_term;
  int64_t last_log_index;
   ::braft::TermLeader disrupted_leader;

  _RequestVoteRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_server_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  void __set_term(const int64_t val);

  void __set_last_log_term(const int64_t val);

  void __set_last_log_index(const int64_t val);

  void __set_disrupted_leader(const  ::braft::TermLeader& val);

  bool operator == (const RequestVoteRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(server_id == rhs.server_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    if (!(term == rhs.term))
      return false;
    if (!(last_log_term == rhs.last_log_term))
      return false;
    if (!(last_log_index == rhs.last_log_index))
      return false;
    if (__isset.disrupted_leader != rhs.__isset.disrupted_leader)
      return false;
    else if (__isset.disrupted_leader && !(disrupted_leader == rhs.disrupted_leader))
      return false;
    return true;
  }
  bool operator != (const RequestVoteRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RequestVoteRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RequestVoteRequest &a, RequestVoteRequest &b);

std::ostream& operator<<(std::ostream& out, const RequestVoteRequest& obj);

typedef struct _RequestVoteResponse__isset {
  _RequestVoteResponse__isset() : term(false), granted(false), disrupted(false), previous_term(false), rejected_by_lease(false) {}
  bool term :1;
  bool granted :1;
  bool disrupted :1;
  bool previous_term :1;
  bool rejected_by_lease :1;
} _RequestVoteResponse__isset;

/**
 * RequestVoteResponse - RequestVote RPC response
 */
class RequestVoteResponse : public virtual ::apache::thrift::TBase {
 public:

  RequestVoteResponse(const RequestVoteResponse&) noexcept;
  RequestVoteResponse& operator=(const RequestVoteResponse&) noexcept;
  RequestVoteResponse() noexcept
                      : term(0),
                        granted(0),
                        disrupted(0),
                        previous_term(0),
                        rejected_by_lease(0) {
  }

  virtual ~RequestVoteResponse() noexcept;
  int64_t term;
  bool granted;
  bool disrupted;
  int64_t previous_term;
  bool rejected_by_lease;

  _RequestVoteResponse__isset __isset;

  void __set_term(const int64_t val);

  void __set_granted(const bool val);

  void __set_disrupted(const bool val);

  void __set_previous_term(const int64_t val);

  void __set_rejected_by_lease(const bool val);

  bool operator == (const RequestVoteResponse & rhs) const
  {
    if (!(term == rhs.term))
      return false;
    if (!(granted == rhs.granted))
      return false;
    if (__isset.disrupted != rhs.__isset.disrupted)
      return false;
    else if (__isset.disrupted && !(disrupted == rhs.disrupted))
      return false;
    if (__isset.previous_term != rhs.__isset.previous_term)
      return false;
    else if (__isset.previous_term && !(previous_term == rhs.previous_term))
      return false;
    if (__isset.rejected_by_lease != rhs.__isset.rejected_by_lease)
      return false;
    else if (__isset.rejected_by_lease && !(rejected_by_lease == rhs.rejected_by_lease))
      return false;
    return true;
  }
  bool operator != (const RequestVoteResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RequestVoteResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RequestVoteResponse &a, RequestVoteResponse &b);

std::ostream& operator<<(std::ostream& out, const RequestVoteResponse& obj);

typedef struct _AppendEntriesRequest__isset {
  _AppendEntriesRequest__isset() : group_id(false), server_id(false), peer_id(false), term(false), prev_log_term(false), prev_log_index(false), entries(false), committed_index(false) {}
  bool group_id :1;
  bool server_id :1;
  bool peer_id :1;
  bool term :1;
  bool prev_log_term :1;
  bool prev_log_index :1;
  bool entries :1;
  bool committed_index :1;
} _AppendEntriesRequest__isset;

/**
 * AppendEntriesRequest - AppendEntries RPC parameters
 * Used for log replication and heartbeat
 */
class AppendEntriesRequest : public virtual ::apache::thrift::TBase {
 public:

  AppendEntriesRequest(const AppendEntriesRequest&);
  AppendEntriesRequest& operator=(const AppendEntriesRequest&);
  AppendEntriesRequest() noexcept
                       : group_id(),
                         server_id(),
                         peer_id(),
                         term(0),
                         prev_log_term(0),
                         prev_log_index(0),
                         committed_index(0) {
  }

  virtual ~AppendEntriesRequest() noexcept;
  std::string group_id;
  std::string server_id;
  std::string peer_id;
  int64_t term;
  int64_t prev_log_term;
  int64_t prev_log_index;
  std::vector< ::braft::EntryMeta>  entries;
  int64_t committed_index;

  _AppendEntriesRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_server_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  void __set_term(const int64_t val);

  void __set_prev_log_term(const int64_t val);

  void __set_prev_log_index(const int64_t val);

  void __set_entries(const std::vector< ::braft::EntryMeta> & val);

  void __set_committed_index(const int64_t val);

  bool operator == (const AppendEntriesRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(server_id == rhs.server_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    if (!(term == rhs.term))
      return false;
    if (!(prev_log_term == rhs.prev_log_term))
      return false;
    if (!(prev_log_index == rhs.prev_log_index))
      return false;
    if (!(entries == rhs.entries))
      return false;
    if (!(committed_index == rhs.committed_index))
      return false;
    return true;
  }
  bool operator != (const AppendEntriesRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AppendEntriesRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AppendEntriesRequest &a, AppendEntriesRequest &b);

std::ostream& operator<<(std::ostream& out, const AppendEntriesRequest& obj);

typedef struct _AppendEntriesResponse__isset {
  _AppendEntriesResponse__isset() : term(false), success(false), last_log_index(false), readonly(false) {}
  bool term :1;
  bool success :1;
  bool last_log_index :1;
  bool readonly :1;
} _AppendEntriesResponse__isset;

/**
 * AppendEntriesResponse - AppendEntries RPC response
 */
class AppendEntriesResponse : public virtual ::apache::thrift::TBase {
 public:

  AppendEntriesResponse(const AppendEntriesResponse&) noexcept;
  AppendEntriesResponse& operator=(const AppendEntriesResponse&) noexcept;
  AppendEntriesResponse() noexcept
                        : term(0),
                          success(0),
                          last_log_index(0),
                          readonly(0) {
  }

  virtual ~AppendEntriesResponse() noexcept;
  int64_t term;
  bool success;
  int64_t last_log_index;
  bool readonly;

  _AppendEntriesResponse__isset __isset;

  void __set_term(const int64_t val);

  void __set_success(const bool val);

  void __set_last_log_index(const int64_t val);

  void __set_readonly(const bool val);

  bool operator == (const AppendEntriesResponse & rhs) const
  {
    if (!(term == rhs.term))
      return false;
    if (!(success == rhs.success))
      return false;
    if (__isset.last_log_index != rhs.__isset.last_log_index)
      return false;
    else if (__isset.last_log_index && !(last_log_index == rhs.last_log_index))
      return false;
    if (__isset.readonly != rhs.__isset.readonly)
      return false;
    else if (__isset.readonly && !(readonly == rhs.readonly))
      return false;
    return true;
  }
  bool operator != (const AppendEntriesResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AppendEntriesResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AppendEntriesResponse &a, AppendEntriesResponse &b);

std::ostream& operator<<(std::ostream& out, const AppendEntriesResponse& obj);

typedef struct _InstallSnapshotRequest__isset {
  _InstallSnapshotRequest__isset() : group_id(false), server_id(false), peer_id(false), term(false), meta(false), uri(false) {}
  bool group_id :1;
  bool server_id :1;
  bool peer_id :1;
  bool term :1;
  bool meta :1;
  bool uri :1;
} _InstallSnapshotRequest__isset;

/**
 * InstallSnapshotRequest - InstallSnapshot RPC parameters
 * Used to send snapshot to lagging followers
 */
class InstallSnapshotRequest : public virtual ::apache::thrift::TBase {
 public:

  InstallSnapshotRequest(const InstallSnapshotRequest&);
  InstallSnapshotRequest& operator=(const InstallSnapshotRequest&);
  InstallSnapshotRequest() noexcept
                         : group_id(),
                           server_id(),
                           peer_id(),
                           term(0),
                           uri() {
  }

  virtual ~InstallSnapshotRequest() noexcept;
  std::string group_id;
  std::string server_id;
  std::string peer_id;
  int64_t term;
   ::braft::SnapshotMeta meta;
  std::string uri;

  _InstallSnapshotRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_server_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  void __set_term(const int64_t val);

  void __set_meta(const  ::braft::SnapshotMeta& val);

  void __set_uri(const std::string& val);

  bool operator == (const InstallSnapshotRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(server_id == rhs.server_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    if (!(term == rhs.term))
      return false;
    if (!(meta == rhs.meta))
      return false;
    if (!(uri == rhs.uri))
      return false;
    return true;
  }
  bool operator != (const InstallSnapshotRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InstallSnapshotRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(InstallSnapshotRequest &a, InstallSnapshotRequest &b);

std::ostream& operator<<(std::ostream& out, const InstallSnapshotRequest& obj);

typedef struct _InstallSnapshotResponse__isset {
  _InstallSnapshotResponse__isset() : term(false), success(false) {}
  bool term :1;
  bool success :1;
} _InstallSnapshotResponse__isset;

/**
 * InstallSnapshotResponse - InstallSnapshot RPC response
 */
class InstallSnapshotResponse : public virtual ::apache::thrift::TBase {
 public:

  InstallSnapshotResponse(const InstallSnapshotResponse&) noexcept;
  InstallSnapshotResponse& operator=(const InstallSnapshotResponse&) noexcept;
  InstallSnapshotResponse() noexcept
                          : term(0),
                            success(0) {
  }

  virtual ~InstallSnapshotResponse() noexcept;
  int64_t term;
  bool success;

  _InstallSnapshotResponse__isset __isset;

  void __set_term(const int64_t val);

  void __set_success(const bool val);

  bool operator == (const InstallSnapshotResponse & rhs) const
  {
    if (!(term == rhs.term))
      return false;
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const InstallSnapshotResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InstallSnapshotResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(InstallSnapshotResponse &a, InstallSnapshotResponse &b);

std::ostream& operator<<(std::ostream& out, const InstallSnapshotResponse& obj);

typedef struct _TimeoutNowRequest__isset {
  _TimeoutNowRequest__isset() : group_id(false), server_id(false), peer_id(false), term(false), old_leader_stepped_down(false) {}
  bool group_id :1;
  bool server_id :1;
  bool peer_id :1;
  bool term :1;
  bool old_leader_stepped_down :1;
} _TimeoutNowRequest__isset;

/**
 * TimeoutNowRequest - TimeoutNow RPC parameters
 * Used to force a follower to start election immediately
 */
class TimeoutNowRequest : public virtual ::apache::thrift::TBase {
 public:

  TimeoutNowRequest(const TimeoutNowRequest&);
  TimeoutNowRequest& operator=(const TimeoutNowRequest&);
  TimeoutNowRequest() noexcept
                    : group_id(),
                      server_id(),
                      peer_id(),
                      term(0),
                      old_leader_stepped_down(0) {
  }

  virtual ~TimeoutNowRequest() noexcept;
  std::string group_id;
  std::string server_id;
  std::string peer_id;
  int64_t term;
  bool old_leader_stepped_down;

  _TimeoutNowRequest__isset __isset;

  void __set_group_id(const std::string& val);

  void __set_server_id(const std::string& val);

  void __set_peer_id(const std::string& val);

  void __set_term(const int64_t val);

  void __set_old_leader_stepped_down(const bool val);

  bool operator == (const TimeoutNowRequest & rhs) const
  {
    if (!(group_id == rhs.group_id))
      return false;
    if (!(server_id == rhs.server_id))
      return false;
    if (!(peer_id == rhs.peer_id))
      return false;
    if (!(term == rhs.term))
      return false;
    if (__isset.old_leader_stepped_down != rhs.__isset.old_leader_stepped_down)
      return false;
    else if (__isset.old_leader_stepped_down && !(old_leader_stepped_down == rhs.old_leader_stepped_down))
      return false;
    return true;
  }
  bool operator != (const TimeoutNowRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimeoutNowRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimeoutNowRequest &a, TimeoutNowRequest &b);

std::ostream& operator<<(std::ostream& out, const TimeoutNowRequest& obj);

typedef struct _TimeoutNowResponse__isset {
  _TimeoutNowResponse__isset() : term(false), success(false) {}
  bool term :1;
  bool success :1;
} _TimeoutNowResponse__isset;

/**
 * TimeoutNowResponse - TimeoutNow RPC response
 */
class TimeoutNowResponse : public virtual ::apache::thrift::TBase {
 public:

  TimeoutNowResponse(const TimeoutNowResponse&) noexcept;
  TimeoutNowResponse& operator=(const TimeoutNowResponse&) noexcept;
  TimeoutNowResponse() noexcept
                     : term(0),
                       success(0) {
  }

  virtual ~TimeoutNowResponse() noexcept;
  int64_t term;
  bool success;

  _TimeoutNowResponse__isset __isset;

  void __set_term(const int64_t val);

  void __set_success(const bool val);

  bool operator == (const TimeoutNowResponse & rhs) const
  {
    if (!(term == rhs.term))
      return false;
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TimeoutNowResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TimeoutNowResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TimeoutNowResponse &a, TimeoutNowResponse &b);

std::ostream& operator<<(std::ostream& out, const TimeoutNowResponse& obj);

} // namespace

#endif
