/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RaftService_H
#define RaftService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "raft_types.h"

namespace braft {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

/**
 * RaftService - Core Raft RPC service
 * All methods support C++20 coroutines via fbthrift
 * 
 * fbthrift will generate coroutine-based methods:
 * - co_preVote(), co_requestVote(), etc.
 * - Use folly::coro::Task<T> as return type for async operations
 */
class RaftServiceIf {
 public:
  virtual ~RaftServiceIf() {}

  /**
   * preVote - Pre-vote phase to avoid disruption
   * Candidate asks if it would receive vote without incrementing term
   * 
   * @param req
   */
  virtual void preVote(RequestVoteResponse& _return, const RequestVoteRequest& req) = 0;

  /**
   * requestVote - Actual vote phase
   * Candidate requests vote from followers
   * 
   * @param req
   */
  virtual void requestVote(RequestVoteResponse& _return, const RequestVoteRequest& req) = 0;

  /**
   * appendEntries - Log replication and heartbeat
   * Leader sends log entries to followers
   * Also used as heartbeat when entries is empty
   * 
   * @param req
   */
  virtual void appendEntries(AppendEntriesResponse& _return, const AppendEntriesRequest& req) = 0;

  /**
   * installSnapshot - Send snapshot to follower
   * Used when follower is too far behind
   * 
   * @param req
   */
  virtual void installSnapshot(InstallSnapshotResponse& _return, const InstallSnapshotRequest& req) = 0;

  /**
   * timeoutNow - Force immediate election
   * Used for leader transfer
   * 
   * @param req
   */
  virtual void timeoutNow(TimeoutNowResponse& _return, const TimeoutNowRequest& req) = 0;
};

class RaftServiceIfFactory {
 public:
  typedef RaftServiceIf Handler;

  virtual ~RaftServiceIfFactory() {}

  virtual RaftServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RaftServiceIf* /* handler */) = 0;
  };

class RaftServiceIfSingletonFactory : virtual public RaftServiceIfFactory {
 public:
  RaftServiceIfSingletonFactory(const ::std::shared_ptr<RaftServiceIf>& iface) : iface_(iface) {}
  virtual ~RaftServiceIfSingletonFactory() {}

  virtual RaftServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(RaftServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<RaftServiceIf> iface_;
};

class RaftServiceNull : virtual public RaftServiceIf {
 public:
  virtual ~RaftServiceNull() {}
  void preVote(RequestVoteResponse& /* _return */, const RequestVoteRequest& /* req */) override {
    return;
  }
  void requestVote(RequestVoteResponse& /* _return */, const RequestVoteRequest& /* req */) override {
    return;
  }
  void appendEntries(AppendEntriesResponse& /* _return */, const AppendEntriesRequest& /* req */) override {
    return;
  }
  void installSnapshot(InstallSnapshotResponse& /* _return */, const InstallSnapshotRequest& /* req */) override {
    return;
  }
  void timeoutNow(TimeoutNowResponse& /* _return */, const TimeoutNowRequest& /* req */) override {
    return;
  }
};

typedef struct _RaftService_preVote_args__isset {
  _RaftService_preVote_args__isset() : req(false) {}
  bool req :1;
} _RaftService_preVote_args__isset;

class RaftService_preVote_args {
 public:

  RaftService_preVote_args(const RaftService_preVote_args&);
  RaftService_preVote_args& operator=(const RaftService_preVote_args&);
  RaftService_preVote_args() noexcept {
  }

  virtual ~RaftService_preVote_args() noexcept;
  RequestVoteRequest req;

  _RaftService_preVote_args__isset __isset;

  void __set_req(const RequestVoteRequest& val);

  bool operator == (const RaftService_preVote_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const RaftService_preVote_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_preVote_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftService_preVote_pargs {
 public:


  virtual ~RaftService_preVote_pargs() noexcept;
  const RequestVoteRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_preVote_result__isset {
  _RaftService_preVote_result__isset() : success(false) {}
  bool success :1;
} _RaftService_preVote_result__isset;

class RaftService_preVote_result {
 public:

  RaftService_preVote_result(const RaftService_preVote_result&) noexcept;
  RaftService_preVote_result& operator=(const RaftService_preVote_result&) noexcept;
  RaftService_preVote_result() noexcept {
  }

  virtual ~RaftService_preVote_result() noexcept;
  RequestVoteResponse success;

  _RaftService_preVote_result__isset __isset;

  void __set_success(const RequestVoteResponse& val);

  bool operator == (const RaftService_preVote_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftService_preVote_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_preVote_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_preVote_presult__isset {
  _RaftService_preVote_presult__isset() : success(false) {}
  bool success :1;
} _RaftService_preVote_presult__isset;

class RaftService_preVote_presult {
 public:


  virtual ~RaftService_preVote_presult() noexcept;
  RequestVoteResponse* success;

  _RaftService_preVote_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RaftService_requestVote_args__isset {
  _RaftService_requestVote_args__isset() : req(false) {}
  bool req :1;
} _RaftService_requestVote_args__isset;

class RaftService_requestVote_args {
 public:

  RaftService_requestVote_args(const RaftService_requestVote_args&);
  RaftService_requestVote_args& operator=(const RaftService_requestVote_args&);
  RaftService_requestVote_args() noexcept {
  }

  virtual ~RaftService_requestVote_args() noexcept;
  RequestVoteRequest req;

  _RaftService_requestVote_args__isset __isset;

  void __set_req(const RequestVoteRequest& val);

  bool operator == (const RaftService_requestVote_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const RaftService_requestVote_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_requestVote_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftService_requestVote_pargs {
 public:


  virtual ~RaftService_requestVote_pargs() noexcept;
  const RequestVoteRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_requestVote_result__isset {
  _RaftService_requestVote_result__isset() : success(false) {}
  bool success :1;
} _RaftService_requestVote_result__isset;

class RaftService_requestVote_result {
 public:

  RaftService_requestVote_result(const RaftService_requestVote_result&) noexcept;
  RaftService_requestVote_result& operator=(const RaftService_requestVote_result&) noexcept;
  RaftService_requestVote_result() noexcept {
  }

  virtual ~RaftService_requestVote_result() noexcept;
  RequestVoteResponse success;

  _RaftService_requestVote_result__isset __isset;

  void __set_success(const RequestVoteResponse& val);

  bool operator == (const RaftService_requestVote_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftService_requestVote_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_requestVote_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_requestVote_presult__isset {
  _RaftService_requestVote_presult__isset() : success(false) {}
  bool success :1;
} _RaftService_requestVote_presult__isset;

class RaftService_requestVote_presult {
 public:


  virtual ~RaftService_requestVote_presult() noexcept;
  RequestVoteResponse* success;

  _RaftService_requestVote_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RaftService_appendEntries_args__isset {
  _RaftService_appendEntries_args__isset() : req(false) {}
  bool req :1;
} _RaftService_appendEntries_args__isset;

class RaftService_appendEntries_args {
 public:

  RaftService_appendEntries_args(const RaftService_appendEntries_args&);
  RaftService_appendEntries_args& operator=(const RaftService_appendEntries_args&);
  RaftService_appendEntries_args() noexcept {
  }

  virtual ~RaftService_appendEntries_args() noexcept;
  AppendEntriesRequest req;

  _RaftService_appendEntries_args__isset __isset;

  void __set_req(const AppendEntriesRequest& val);

  bool operator == (const RaftService_appendEntries_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const RaftService_appendEntries_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_appendEntries_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftService_appendEntries_pargs {
 public:


  virtual ~RaftService_appendEntries_pargs() noexcept;
  const AppendEntriesRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_appendEntries_result__isset {
  _RaftService_appendEntries_result__isset() : success(false) {}
  bool success :1;
} _RaftService_appendEntries_result__isset;

class RaftService_appendEntries_result {
 public:

  RaftService_appendEntries_result(const RaftService_appendEntries_result&) noexcept;
  RaftService_appendEntries_result& operator=(const RaftService_appendEntries_result&) noexcept;
  RaftService_appendEntries_result() noexcept {
  }

  virtual ~RaftService_appendEntries_result() noexcept;
  AppendEntriesResponse success;

  _RaftService_appendEntries_result__isset __isset;

  void __set_success(const AppendEntriesResponse& val);

  bool operator == (const RaftService_appendEntries_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftService_appendEntries_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_appendEntries_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_appendEntries_presult__isset {
  _RaftService_appendEntries_presult__isset() : success(false) {}
  bool success :1;
} _RaftService_appendEntries_presult__isset;

class RaftService_appendEntries_presult {
 public:


  virtual ~RaftService_appendEntries_presult() noexcept;
  AppendEntriesResponse* success;

  _RaftService_appendEntries_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RaftService_installSnapshot_args__isset {
  _RaftService_installSnapshot_args__isset() : req(false) {}
  bool req :1;
} _RaftService_installSnapshot_args__isset;

class RaftService_installSnapshot_args {
 public:

  RaftService_installSnapshot_args(const RaftService_installSnapshot_args&);
  RaftService_installSnapshot_args& operator=(const RaftService_installSnapshot_args&);
  RaftService_installSnapshot_args() noexcept {
  }

  virtual ~RaftService_installSnapshot_args() noexcept;
  InstallSnapshotRequest req;

  _RaftService_installSnapshot_args__isset __isset;

  void __set_req(const InstallSnapshotRequest& val);

  bool operator == (const RaftService_installSnapshot_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const RaftService_installSnapshot_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_installSnapshot_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftService_installSnapshot_pargs {
 public:


  virtual ~RaftService_installSnapshot_pargs() noexcept;
  const InstallSnapshotRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_installSnapshot_result__isset {
  _RaftService_installSnapshot_result__isset() : success(false) {}
  bool success :1;
} _RaftService_installSnapshot_result__isset;

class RaftService_installSnapshot_result {
 public:

  RaftService_installSnapshot_result(const RaftService_installSnapshot_result&) noexcept;
  RaftService_installSnapshot_result& operator=(const RaftService_installSnapshot_result&) noexcept;
  RaftService_installSnapshot_result() noexcept {
  }

  virtual ~RaftService_installSnapshot_result() noexcept;
  InstallSnapshotResponse success;

  _RaftService_installSnapshot_result__isset __isset;

  void __set_success(const InstallSnapshotResponse& val);

  bool operator == (const RaftService_installSnapshot_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftService_installSnapshot_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_installSnapshot_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_installSnapshot_presult__isset {
  _RaftService_installSnapshot_presult__isset() : success(false) {}
  bool success :1;
} _RaftService_installSnapshot_presult__isset;

class RaftService_installSnapshot_presult {
 public:


  virtual ~RaftService_installSnapshot_presult() noexcept;
  InstallSnapshotResponse* success;

  _RaftService_installSnapshot_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RaftService_timeoutNow_args__isset {
  _RaftService_timeoutNow_args__isset() : req(false) {}
  bool req :1;
} _RaftService_timeoutNow_args__isset;

class RaftService_timeoutNow_args {
 public:

  RaftService_timeoutNow_args(const RaftService_timeoutNow_args&);
  RaftService_timeoutNow_args& operator=(const RaftService_timeoutNow_args&);
  RaftService_timeoutNow_args() noexcept {
  }

  virtual ~RaftService_timeoutNow_args() noexcept;
  TimeoutNowRequest req;

  _RaftService_timeoutNow_args__isset __isset;

  void __set_req(const TimeoutNowRequest& val);

  bool operator == (const RaftService_timeoutNow_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const RaftService_timeoutNow_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_timeoutNow_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RaftService_timeoutNow_pargs {
 public:


  virtual ~RaftService_timeoutNow_pargs() noexcept;
  const TimeoutNowRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_timeoutNow_result__isset {
  _RaftService_timeoutNow_result__isset() : success(false) {}
  bool success :1;
} _RaftService_timeoutNow_result__isset;

class RaftService_timeoutNow_result {
 public:

  RaftService_timeoutNow_result(const RaftService_timeoutNow_result&) noexcept;
  RaftService_timeoutNow_result& operator=(const RaftService_timeoutNow_result&) noexcept;
  RaftService_timeoutNow_result() noexcept {
  }

  virtual ~RaftService_timeoutNow_result() noexcept;
  TimeoutNowResponse success;

  _RaftService_timeoutNow_result__isset __isset;

  void __set_success(const TimeoutNowResponse& val);

  bool operator == (const RaftService_timeoutNow_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RaftService_timeoutNow_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RaftService_timeoutNow_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RaftService_timeoutNow_presult__isset {
  _RaftService_timeoutNow_presult__isset() : success(false) {}
  bool success :1;
} _RaftService_timeoutNow_presult__isset;

class RaftService_timeoutNow_presult {
 public:


  virtual ~RaftService_timeoutNow_presult() noexcept;
  TimeoutNowResponse* success;

  _RaftService_timeoutNow_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RaftServiceClient : virtual public RaftServiceIf {
 public:
  RaftServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RaftServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * preVote - Pre-vote phase to avoid disruption
   * Candidate asks if it would receive vote without incrementing term
   * 
   * @param req
   */
  void preVote(RequestVoteResponse& _return, const RequestVoteRequest& req) override;
  void send_preVote(const RequestVoteRequest& req);
  void recv_preVote(RequestVoteResponse& _return);
  /**
   * requestVote - Actual vote phase
   * Candidate requests vote from followers
   * 
   * @param req
   */
  void requestVote(RequestVoteResponse& _return, const RequestVoteRequest& req) override;
  void send_requestVote(const RequestVoteRequest& req);
  void recv_requestVote(RequestVoteResponse& _return);
  /**
   * appendEntries - Log replication and heartbeat
   * Leader sends log entries to followers
   * Also used as heartbeat when entries is empty
   * 
   * @param req
   */
  void appendEntries(AppendEntriesResponse& _return, const AppendEntriesRequest& req) override;
  void send_appendEntries(const AppendEntriesRequest& req);
  void recv_appendEntries(AppendEntriesResponse& _return);
  /**
   * installSnapshot - Send snapshot to follower
   * Used when follower is too far behind
   * 
   * @param req
   */
  void installSnapshot(InstallSnapshotResponse& _return, const InstallSnapshotRequest& req) override;
  void send_installSnapshot(const InstallSnapshotRequest& req);
  void recv_installSnapshot(InstallSnapshotResponse& _return);
  /**
   * timeoutNow - Force immediate election
   * Used for leader transfer
   * 
   * @param req
   */
  void timeoutNow(TimeoutNowResponse& _return, const TimeoutNowRequest& req) override;
  void send_timeoutNow(const TimeoutNowRequest& req);
  void recv_timeoutNow(TimeoutNowResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RaftServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<RaftServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (RaftServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_preVote(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_requestVote(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_appendEntries(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_installSnapshot(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_timeoutNow(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RaftServiceProcessor(::std::shared_ptr<RaftServiceIf> iface) :
    iface_(iface) {
    processMap_["preVote"] = &RaftServiceProcessor::process_preVote;
    processMap_["requestVote"] = &RaftServiceProcessor::process_requestVote;
    processMap_["appendEntries"] = &RaftServiceProcessor::process_appendEntries;
    processMap_["installSnapshot"] = &RaftServiceProcessor::process_installSnapshot;
    processMap_["timeoutNow"] = &RaftServiceProcessor::process_timeoutNow;
  }

  virtual ~RaftServiceProcessor() {}
};

class RaftServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RaftServiceProcessorFactory(const ::std::shared_ptr< RaftServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< RaftServiceIfFactory > handlerFactory_;
};

class RaftServiceMultiface : virtual public RaftServiceIf {
 public:
  RaftServiceMultiface(std::vector<std::shared_ptr<RaftServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RaftServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<RaftServiceIf> > ifaces_;
  RaftServiceMultiface() {}
  void add(::std::shared_ptr<RaftServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * preVote - Pre-vote phase to avoid disruption
   * Candidate asks if it would receive vote without incrementing term
   * 
   * @param req
   */
  void preVote(RequestVoteResponse& _return, const RequestVoteRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->preVote(_return, req);
    }
    ifaces_[i]->preVote(_return, req);
    return;
  }

  /**
   * requestVote - Actual vote phase
   * Candidate requests vote from followers
   * 
   * @param req
   */
  void requestVote(RequestVoteResponse& _return, const RequestVoteRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->requestVote(_return, req);
    }
    ifaces_[i]->requestVote(_return, req);
    return;
  }

  /**
   * appendEntries - Log replication and heartbeat
   * Leader sends log entries to followers
   * Also used as heartbeat when entries is empty
   * 
   * @param req
   */
  void appendEntries(AppendEntriesResponse& _return, const AppendEntriesRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->appendEntries(_return, req);
    }
    ifaces_[i]->appendEntries(_return, req);
    return;
  }

  /**
   * installSnapshot - Send snapshot to follower
   * Used when follower is too far behind
   * 
   * @param req
   */
  void installSnapshot(InstallSnapshotResponse& _return, const InstallSnapshotRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->installSnapshot(_return, req);
    }
    ifaces_[i]->installSnapshot(_return, req);
    return;
  }

  /**
   * timeoutNow - Force immediate election
   * Used for leader transfer
   * 
   * @param req
   */
  void timeoutNow(TimeoutNowResponse& _return, const TimeoutNowRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->timeoutNow(_return, req);
    }
    ifaces_[i]->timeoutNow(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class RaftServiceConcurrentClient : virtual public RaftServiceIf {
 public:
  RaftServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  RaftServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * preVote - Pre-vote phase to avoid disruption
   * Candidate asks if it would receive vote without incrementing term
   * 
   * @param req
   */
  void preVote(RequestVoteResponse& _return, const RequestVoteRequest& req) override;
  int32_t send_preVote(const RequestVoteRequest& req);
  void recv_preVote(RequestVoteResponse& _return, const int32_t seqid);
  /**
   * requestVote - Actual vote phase
   * Candidate requests vote from followers
   * 
   * @param req
   */
  void requestVote(RequestVoteResponse& _return, const RequestVoteRequest& req) override;
  int32_t send_requestVote(const RequestVoteRequest& req);
  void recv_requestVote(RequestVoteResponse& _return, const int32_t seqid);
  /**
   * appendEntries - Log replication and heartbeat
   * Leader sends log entries to followers
   * Also used as heartbeat when entries is empty
   * 
   * @param req
   */
  void appendEntries(AppendEntriesResponse& _return, const AppendEntriesRequest& req) override;
  int32_t send_appendEntries(const AppendEntriesRequest& req);
  void recv_appendEntries(AppendEntriesResponse& _return, const int32_t seqid);
  /**
   * installSnapshot - Send snapshot to follower
   * Used when follower is too far behind
   * 
   * @param req
   */
  void installSnapshot(InstallSnapshotResponse& _return, const InstallSnapshotRequest& req) override;
  int32_t send_installSnapshot(const InstallSnapshotRequest& req);
  void recv_installSnapshot(InstallSnapshotResponse& _return, const int32_t seqid);
  /**
   * timeoutNow - Force immediate election
   * Used for leader transfer
   * 
   * @param req
   */
  void timeoutNow(TimeoutNowResponse& _return, const TimeoutNowRequest& req) override;
  int32_t send_timeoutNow(const TimeoutNowRequest& req);
  void recv_timeoutNow(TimeoutNowResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
