// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RaftService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::braft;

class RaftServiceHandler : virtual public RaftServiceIf {
 public:
  RaftServiceHandler() {
    // Your initialization goes here
  }

  /**
   * preVote - Pre-vote phase to avoid disruption
   * Candidate asks if it would receive vote without incrementing term
   * 
   * @param req
   */
  void preVote(RequestVoteResponse& _return, const RequestVoteRequest& req) {
    // Your implementation goes here
    printf("preVote\n");
  }

  /**
   * requestVote - Actual vote phase
   * Candidate requests vote from followers
   * 
   * @param req
   */
  void requestVote(RequestVoteResponse& _return, const RequestVoteRequest& req) {
    // Your implementation goes here
    printf("requestVote\n");
  }

  /**
   * appendEntries - Log replication and heartbeat
   * Leader sends log entries to followers
   * Also used as heartbeat when entries is empty
   * 
   * @param req
   */
  void appendEntries(AppendEntriesResponse& _return, const AppendEntriesRequest& req) {
    // Your implementation goes here
    printf("appendEntries\n");
  }

  /**
   * installSnapshot - Send snapshot to follower
   * Used when follower is too far behind
   * 
   * @param req
   */
  void installSnapshot(InstallSnapshotResponse& _return, const InstallSnapshotRequest& req) {
    // Your implementation goes here
    printf("installSnapshot\n");
  }

  /**
   * timeoutNow - Force immediate election
   * Used for leader transfer
   * 
   * @param req
   */
  void timeoutNow(TimeoutNowResponse& _return, const TimeoutNowRequest& req) {
    // Your implementation goes here
    printf("timeoutNow\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<RaftServiceHandler> handler(new RaftServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new RaftServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

