/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "raft_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace braft {


RequestVoteRequest::~RequestVoteRequest() noexcept {
}


void RequestVoteRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void RequestVoteRequest::__set_server_id(const std::string& val) {
  this->server_id = val;
}

void RequestVoteRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}

void RequestVoteRequest::__set_term(const int64_t val) {
  this->term = val;
}

void RequestVoteRequest::__set_last_log_term(const int64_t val) {
  this->last_log_term = val;
}

void RequestVoteRequest::__set_last_log_index(const int64_t val) {
  this->last_log_index = val;
}

void RequestVoteRequest::__set_disrupted_leader(const  ::braft::TermLeader& val) {
  this->disrupted_leader = val;
__isset.disrupted_leader = true;
}
std::ostream& operator<<(std::ostream& out, const RequestVoteRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t RequestVoteRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->server_id);
          this->__isset.server_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->last_log_term);
          this->__isset.last_log_term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->last_log_index);
          this->__isset.last_log_index = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->disrupted_leader.read(iprot);
          this->__isset.disrupted_leader = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RequestVoteRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("RequestVoteRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("server_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->server_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("last_log_term", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->last_log_term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("last_log_index", ::apache::thrift::protocol::T_I64, 6);
  xfer += oprot->writeI64(this->last_log_index);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.disrupted_leader) {
    xfer += oprot->writeFieldBegin("disrupted_leader", ::apache::thrift::protocol::T_STRUCT, 7);
    xfer += this->disrupted_leader.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RequestVoteRequest &a, RequestVoteRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.server_id, b.server_id);
  swap(a.peer_id, b.peer_id);
  swap(a.term, b.term);
  swap(a.last_log_term, b.last_log_term);
  swap(a.last_log_index, b.last_log_index);
  swap(a.disrupted_leader, b.disrupted_leader);
  swap(a.__isset, b.__isset);
}

RequestVoteRequest::RequestVoteRequest(const RequestVoteRequest& other0) {
  group_id = other0.group_id;
  server_id = other0.server_id;
  peer_id = other0.peer_id;
  term = other0.term;
  last_log_term = other0.last_log_term;
  last_log_index = other0.last_log_index;
  disrupted_leader = other0.disrupted_leader;
  __isset = other0.__isset;
}
RequestVoteRequest& RequestVoteRequest::operator=(const RequestVoteRequest& other1) {
  group_id = other1.group_id;
  server_id = other1.server_id;
  peer_id = other1.peer_id;
  term = other1.term;
  last_log_term = other1.last_log_term;
  last_log_index = other1.last_log_index;
  disrupted_leader = other1.disrupted_leader;
  __isset = other1.__isset;
  return *this;
}
void RequestVoteRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "RequestVoteRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "server_id=" << to_string(server_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ", " << "term=" << to_string(term);
  out << ", " << "last_log_term=" << to_string(last_log_term);
  out << ", " << "last_log_index=" << to_string(last_log_index);
  out << ", " << "disrupted_leader="; (__isset.disrupted_leader ? (out << to_string(disrupted_leader)) : (out << "<null>"));
  out << ")";
}


RequestVoteResponse::~RequestVoteResponse() noexcept {
}


void RequestVoteResponse::__set_term(const int64_t val) {
  this->term = val;
}

void RequestVoteResponse::__set_granted(const bool val) {
  this->granted = val;
}

void RequestVoteResponse::__set_disrupted(const bool val) {
  this->disrupted = val;
__isset.disrupted = true;
}

void RequestVoteResponse::__set_previous_term(const int64_t val) {
  this->previous_term = val;
__isset.previous_term = true;
}

void RequestVoteResponse::__set_rejected_by_lease(const bool val) {
  this->rejected_by_lease = val;
__isset.rejected_by_lease = true;
}
std::ostream& operator<<(std::ostream& out, const RequestVoteResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t RequestVoteResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->granted);
          this->__isset.granted = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->disrupted);
          this->__isset.disrupted = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->previous_term);
          this->__isset.previous_term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->rejected_by_lease);
          this->__isset.rejected_by_lease = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t RequestVoteResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("RequestVoteResponse");

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("granted", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->granted);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.disrupted) {
    xfer += oprot->writeFieldBegin("disrupted", ::apache::thrift::protocol::T_BOOL, 3);
    xfer += oprot->writeBool(this->disrupted);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.previous_term) {
    xfer += oprot->writeFieldBegin("previous_term", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->previous_term);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.rejected_by_lease) {
    xfer += oprot->writeFieldBegin("rejected_by_lease", ::apache::thrift::protocol::T_BOOL, 5);
    xfer += oprot->writeBool(this->rejected_by_lease);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(RequestVoteResponse &a, RequestVoteResponse &b) {
  using ::std::swap;
  swap(a.term, b.term);
  swap(a.granted, b.granted);
  swap(a.disrupted, b.disrupted);
  swap(a.previous_term, b.previous_term);
  swap(a.rejected_by_lease, b.rejected_by_lease);
  swap(a.__isset, b.__isset);
}

RequestVoteResponse::RequestVoteResponse(const RequestVoteResponse& other2) noexcept {
  term = other2.term;
  granted = other2.granted;
  disrupted = other2.disrupted;
  previous_term = other2.previous_term;
  rejected_by_lease = other2.rejected_by_lease;
  __isset = other2.__isset;
}
RequestVoteResponse& RequestVoteResponse::operator=(const RequestVoteResponse& other3) noexcept {
  term = other3.term;
  granted = other3.granted;
  disrupted = other3.disrupted;
  previous_term = other3.previous_term;
  rejected_by_lease = other3.rejected_by_lease;
  __isset = other3.__isset;
  return *this;
}
void RequestVoteResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "RequestVoteResponse(";
  out << "term=" << to_string(term);
  out << ", " << "granted=" << to_string(granted);
  out << ", " << "disrupted="; (__isset.disrupted ? (out << to_string(disrupted)) : (out << "<null>"));
  out << ", " << "previous_term="; (__isset.previous_term ? (out << to_string(previous_term)) : (out << "<null>"));
  out << ", " << "rejected_by_lease="; (__isset.rejected_by_lease ? (out << to_string(rejected_by_lease)) : (out << "<null>"));
  out << ")";
}


AppendEntriesRequest::~AppendEntriesRequest() noexcept {
}


void AppendEntriesRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void AppendEntriesRequest::__set_server_id(const std::string& val) {
  this->server_id = val;
}

void AppendEntriesRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}

void AppendEntriesRequest::__set_term(const int64_t val) {
  this->term = val;
}

void AppendEntriesRequest::__set_prev_log_term(const int64_t val) {
  this->prev_log_term = val;
}

void AppendEntriesRequest::__set_prev_log_index(const int64_t val) {
  this->prev_log_index = val;
}

void AppendEntriesRequest::__set_entries(const std::vector< ::braft::EntryMeta> & val) {
  this->entries = val;
}

void AppendEntriesRequest::__set_committed_index(const int64_t val) {
  this->committed_index = val;
}
std::ostream& operator<<(std::ostream& out, const AppendEntriesRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AppendEntriesRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->server_id);
          this->__isset.server_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->prev_log_term);
          this->__isset.prev_log_term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->prev_log_index);
          this->__isset.prev_log_index = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->entries.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->entries.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->entries[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.entries = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->committed_index);
          this->__isset.committed_index = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AppendEntriesRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AppendEntriesRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("server_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->server_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("prev_log_term", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->prev_log_term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("prev_log_index", ::apache::thrift::protocol::T_I64, 6);
  xfer += oprot->writeI64(this->prev_log_index);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("entries", ::apache::thrift::protocol::T_LIST, 7);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->entries.size()));
    std::vector< ::braft::EntryMeta> ::const_iterator _iter9;
    for (_iter9 = this->entries.begin(); _iter9 != this->entries.end(); ++_iter9)
    {
      xfer += (*_iter9).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("committed_index", ::apache::thrift::protocol::T_I64, 8);
  xfer += oprot->writeI64(this->committed_index);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AppendEntriesRequest &a, AppendEntriesRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.server_id, b.server_id);
  swap(a.peer_id, b.peer_id);
  swap(a.term, b.term);
  swap(a.prev_log_term, b.prev_log_term);
  swap(a.prev_log_index, b.prev_log_index);
  swap(a.entries, b.entries);
  swap(a.committed_index, b.committed_index);
  swap(a.__isset, b.__isset);
}

AppendEntriesRequest::AppendEntriesRequest(const AppendEntriesRequest& other10) {
  group_id = other10.group_id;
  server_id = other10.server_id;
  peer_id = other10.peer_id;
  term = other10.term;
  prev_log_term = other10.prev_log_term;
  prev_log_index = other10.prev_log_index;
  entries = other10.entries;
  committed_index = other10.committed_index;
  __isset = other10.__isset;
}
AppendEntriesRequest& AppendEntriesRequest::operator=(const AppendEntriesRequest& other11) {
  group_id = other11.group_id;
  server_id = other11.server_id;
  peer_id = other11.peer_id;
  term = other11.term;
  prev_log_term = other11.prev_log_term;
  prev_log_index = other11.prev_log_index;
  entries = other11.entries;
  committed_index = other11.committed_index;
  __isset = other11.__isset;
  return *this;
}
void AppendEntriesRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AppendEntriesRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "server_id=" << to_string(server_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ", " << "term=" << to_string(term);
  out << ", " << "prev_log_term=" << to_string(prev_log_term);
  out << ", " << "prev_log_index=" << to_string(prev_log_index);
  out << ", " << "entries=" << to_string(entries);
  out << ", " << "committed_index=" << to_string(committed_index);
  out << ")";
}


AppendEntriesResponse::~AppendEntriesResponse() noexcept {
}


void AppendEntriesResponse::__set_term(const int64_t val) {
  this->term = val;
}

void AppendEntriesResponse::__set_success(const bool val) {
  this->success = val;
}

void AppendEntriesResponse::__set_last_log_index(const int64_t val) {
  this->last_log_index = val;
__isset.last_log_index = true;
}

void AppendEntriesResponse::__set_readonly(const bool val) {
  this->readonly = val;
__isset.readonly = true;
}
std::ostream& operator<<(std::ostream& out, const AppendEntriesResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AppendEntriesResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->success);
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->last_log_index);
          this->__isset.last_log_index = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->readonly);
          this->__isset.readonly = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AppendEntriesResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AppendEntriesResponse");

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("success", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->success);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.last_log_index) {
    xfer += oprot->writeFieldBegin("last_log_index", ::apache::thrift::protocol::T_I64, 3);
    xfer += oprot->writeI64(this->last_log_index);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.readonly) {
    xfer += oprot->writeFieldBegin("readonly", ::apache::thrift::protocol::T_BOOL, 4);
    xfer += oprot->writeBool(this->readonly);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AppendEntriesResponse &a, AppendEntriesResponse &b) {
  using ::std::swap;
  swap(a.term, b.term);
  swap(a.success, b.success);
  swap(a.last_log_index, b.last_log_index);
  swap(a.readonly, b.readonly);
  swap(a.__isset, b.__isset);
}

AppendEntriesResponse::AppendEntriesResponse(const AppendEntriesResponse& other12) noexcept {
  term = other12.term;
  success = other12.success;
  last_log_index = other12.last_log_index;
  readonly = other12.readonly;
  __isset = other12.__isset;
}
AppendEntriesResponse& AppendEntriesResponse::operator=(const AppendEntriesResponse& other13) noexcept {
  term = other13.term;
  success = other13.success;
  last_log_index = other13.last_log_index;
  readonly = other13.readonly;
  __isset = other13.__isset;
  return *this;
}
void AppendEntriesResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AppendEntriesResponse(";
  out << "term=" << to_string(term);
  out << ", " << "success=" << to_string(success);
  out << ", " << "last_log_index="; (__isset.last_log_index ? (out << to_string(last_log_index)) : (out << "<null>"));
  out << ", " << "readonly="; (__isset.readonly ? (out << to_string(readonly)) : (out << "<null>"));
  out << ")";
}


InstallSnapshotRequest::~InstallSnapshotRequest() noexcept {
}


void InstallSnapshotRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void InstallSnapshotRequest::__set_server_id(const std::string& val) {
  this->server_id = val;
}

void InstallSnapshotRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}

void InstallSnapshotRequest::__set_term(const int64_t val) {
  this->term = val;
}

void InstallSnapshotRequest::__set_meta(const  ::braft::SnapshotMeta& val) {
  this->meta = val;
}

void InstallSnapshotRequest::__set_uri(const std::string& val) {
  this->uri = val;
}
std::ostream& operator<<(std::ostream& out, const InstallSnapshotRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t InstallSnapshotRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->server_id);
          this->__isset.server_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->meta.read(iprot);
          this->__isset.meta = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->uri);
          this->__isset.uri = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InstallSnapshotRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("InstallSnapshotRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("server_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->server_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("meta", ::apache::thrift::protocol::T_STRUCT, 5);
  xfer += this->meta.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("uri", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->uri);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(InstallSnapshotRequest &a, InstallSnapshotRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.server_id, b.server_id);
  swap(a.peer_id, b.peer_id);
  swap(a.term, b.term);
  swap(a.meta, b.meta);
  swap(a.uri, b.uri);
  swap(a.__isset, b.__isset);
}

InstallSnapshotRequest::InstallSnapshotRequest(const InstallSnapshotRequest& other14) {
  group_id = other14.group_id;
  server_id = other14.server_id;
  peer_id = other14.peer_id;
  term = other14.term;
  meta = other14.meta;
  uri = other14.uri;
  __isset = other14.__isset;
}
InstallSnapshotRequest& InstallSnapshotRequest::operator=(const InstallSnapshotRequest& other15) {
  group_id = other15.group_id;
  server_id = other15.server_id;
  peer_id = other15.peer_id;
  term = other15.term;
  meta = other15.meta;
  uri = other15.uri;
  __isset = other15.__isset;
  return *this;
}
void InstallSnapshotRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "InstallSnapshotRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "server_id=" << to_string(server_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ", " << "term=" << to_string(term);
  out << ", " << "meta=" << to_string(meta);
  out << ", " << "uri=" << to_string(uri);
  out << ")";
}


InstallSnapshotResponse::~InstallSnapshotResponse() noexcept {
}


void InstallSnapshotResponse::__set_term(const int64_t val) {
  this->term = val;
}

void InstallSnapshotResponse::__set_success(const bool val) {
  this->success = val;
}
std::ostream& operator<<(std::ostream& out, const InstallSnapshotResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t InstallSnapshotResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->success);
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InstallSnapshotResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("InstallSnapshotResponse");

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("success", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->success);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(InstallSnapshotResponse &a, InstallSnapshotResponse &b) {
  using ::std::swap;
  swap(a.term, b.term);
  swap(a.success, b.success);
  swap(a.__isset, b.__isset);
}

InstallSnapshotResponse::InstallSnapshotResponse(const InstallSnapshotResponse& other16) noexcept {
  term = other16.term;
  success = other16.success;
  __isset = other16.__isset;
}
InstallSnapshotResponse& InstallSnapshotResponse::operator=(const InstallSnapshotResponse& other17) noexcept {
  term = other17.term;
  success = other17.success;
  __isset = other17.__isset;
  return *this;
}
void InstallSnapshotResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "InstallSnapshotResponse(";
  out << "term=" << to_string(term);
  out << ", " << "success=" << to_string(success);
  out << ")";
}


TimeoutNowRequest::~TimeoutNowRequest() noexcept {
}


void TimeoutNowRequest::__set_group_id(const std::string& val) {
  this->group_id = val;
}

void TimeoutNowRequest::__set_server_id(const std::string& val) {
  this->server_id = val;
}

void TimeoutNowRequest::__set_peer_id(const std::string& val) {
  this->peer_id = val;
}

void TimeoutNowRequest::__set_term(const int64_t val) {
  this->term = val;
}

void TimeoutNowRequest::__set_old_leader_stepped_down(const bool val) {
  this->old_leader_stepped_down = val;
__isset.old_leader_stepped_down = true;
}
std::ostream& operator<<(std::ostream& out, const TimeoutNowRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TimeoutNowRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->group_id);
          this->__isset.group_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->server_id);
          this->__isset.server_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->peer_id);
          this->__isset.peer_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->old_leader_stepped_down);
          this->__isset.old_leader_stepped_down = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TimeoutNowRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TimeoutNowRequest");

  xfer += oprot->writeFieldBegin("group_id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->group_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("server_id", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->server_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peer_id", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->peer_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.old_leader_stepped_down) {
    xfer += oprot->writeFieldBegin("old_leader_stepped_down", ::apache::thrift::protocol::T_BOOL, 5);
    xfer += oprot->writeBool(this->old_leader_stepped_down);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TimeoutNowRequest &a, TimeoutNowRequest &b) {
  using ::std::swap;
  swap(a.group_id, b.group_id);
  swap(a.server_id, b.server_id);
  swap(a.peer_id, b.peer_id);
  swap(a.term, b.term);
  swap(a.old_leader_stepped_down, b.old_leader_stepped_down);
  swap(a.__isset, b.__isset);
}

TimeoutNowRequest::TimeoutNowRequest(const TimeoutNowRequest& other18) {
  group_id = other18.group_id;
  server_id = other18.server_id;
  peer_id = other18.peer_id;
  term = other18.term;
  old_leader_stepped_down = other18.old_leader_stepped_down;
  __isset = other18.__isset;
}
TimeoutNowRequest& TimeoutNowRequest::operator=(const TimeoutNowRequest& other19) {
  group_id = other19.group_id;
  server_id = other19.server_id;
  peer_id = other19.peer_id;
  term = other19.term;
  old_leader_stepped_down = other19.old_leader_stepped_down;
  __isset = other19.__isset;
  return *this;
}
void TimeoutNowRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TimeoutNowRequest(";
  out << "group_id=" << to_string(group_id);
  out << ", " << "server_id=" << to_string(server_id);
  out << ", " << "peer_id=" << to_string(peer_id);
  out << ", " << "term=" << to_string(term);
  out << ", " << "old_leader_stepped_down="; (__isset.old_leader_stepped_down ? (out << to_string(old_leader_stepped_down)) : (out << "<null>"));
  out << ")";
}


TimeoutNowResponse::~TimeoutNowResponse() noexcept {
}


void TimeoutNowResponse::__set_term(const int64_t val) {
  this->term = val;
}

void TimeoutNowResponse::__set_success(const bool val) {
  this->success = val;
}
std::ostream& operator<<(std::ostream& out, const TimeoutNowResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TimeoutNowResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->success);
          this->__isset.success = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TimeoutNowResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TimeoutNowResponse");

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("success", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->success);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TimeoutNowResponse &a, TimeoutNowResponse &b) {
  using ::std::swap;
  swap(a.term, b.term);
  swap(a.success, b.success);
  swap(a.__isset, b.__isset);
}

TimeoutNowResponse::TimeoutNowResponse(const TimeoutNowResponse& other20) noexcept {
  term = other20.term;
  success = other20.success;
  __isset = other20.__isset;
}
TimeoutNowResponse& TimeoutNowResponse::operator=(const TimeoutNowResponse& other21) noexcept {
  term = other21.term;
  success = other21.success;
  __isset = other21.__isset;
  return *this;
}
void TimeoutNowResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TimeoutNowResponse(";
  out << "term=" << to_string(term);
  out << ", " << "success=" << to_string(success);
  out << ")";
}

} // namespace
