/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace braft {


ConfigurationPBMeta::~ConfigurationPBMeta() noexcept {
}


void ConfigurationPBMeta::__set_peers(const std::vector<std::string> & val) {
  this->peers = val;
}

void ConfigurationPBMeta::__set_old_peers(const std::vector<std::string> & val) {
  this->old_peers = val;
}
std::ostream& operator<<(std::ostream& out, const ConfigurationPBMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ConfigurationPBMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->peers.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->peers.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readString(this->peers[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->old_peers.clear();
            uint32_t _size5;
            ::apache::thrift::protocol::TType _etype8;
            xfer += iprot->readListBegin(_etype8, _size5);
            this->old_peers.resize(_size5);
            uint32_t _i9;
            for (_i9 = 0; _i9 < _size5; ++_i9)
            {
              xfer += iprot->readString(this->old_peers[_i9]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.old_peers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ConfigurationPBMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ConfigurationPBMeta");

  xfer += oprot->writeFieldBegin("peers", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->peers.size()));
    std::vector<std::string> ::const_iterator _iter10;
    for (_iter10 = this->peers.begin(); _iter10 != this->peers.end(); ++_iter10)
    {
      xfer += oprot->writeString((*_iter10));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("old_peers", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->old_peers.size()));
    std::vector<std::string> ::const_iterator _iter11;
    for (_iter11 = this->old_peers.begin(); _iter11 != this->old_peers.end(); ++_iter11)
    {
      xfer += oprot->writeString((*_iter11));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ConfigurationPBMeta &a, ConfigurationPBMeta &b) {
  using ::std::swap;
  swap(a.peers, b.peers);
  swap(a.old_peers, b.old_peers);
  swap(a.__isset, b.__isset);
}

ConfigurationPBMeta::ConfigurationPBMeta(const ConfigurationPBMeta& other12) {
  peers = other12.peers;
  old_peers = other12.old_peers;
  __isset = other12.__isset;
}
ConfigurationPBMeta& ConfigurationPBMeta::operator=(const ConfigurationPBMeta& other13) {
  peers = other13.peers;
  old_peers = other13.old_peers;
  __isset = other13.__isset;
  return *this;
}
void ConfigurationPBMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ConfigurationPBMeta(";
  out << "peers=" << to_string(peers);
  out << ", " << "old_peers=" << to_string(old_peers);
  out << ")";
}


LogPBMeta::~LogPBMeta() noexcept {
}


void LogPBMeta::__set_first_log_index(const int64_t val) {
  this->first_log_index = val;
}
std::ostream& operator<<(std::ostream& out, const LogPBMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LogPBMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->first_log_index);
          this->__isset.first_log_index = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LogPBMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LogPBMeta");

  xfer += oprot->writeFieldBegin("first_log_index", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->first_log_index);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LogPBMeta &a, LogPBMeta &b) {
  using ::std::swap;
  swap(a.first_log_index, b.first_log_index);
  swap(a.__isset, b.__isset);
}

LogPBMeta::LogPBMeta(const LogPBMeta& other14) noexcept {
  first_log_index = other14.first_log_index;
  __isset = other14.__isset;
}
LogPBMeta& LogPBMeta::operator=(const LogPBMeta& other15) noexcept {
  first_log_index = other15.first_log_index;
  __isset = other15.__isset;
  return *this;
}
void LogPBMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LogPBMeta(";
  out << "first_log_index=" << to_string(first_log_index);
  out << ")";
}


StablePBMeta::~StablePBMeta() noexcept {
}


void StablePBMeta::__set_term(const int64_t val) {
  this->term = val;
}

void StablePBMeta::__set_votedfor(const std::string& val) {
  this->votedfor = val;
}
std::ostream& operator<<(std::ostream& out, const StablePBMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StablePBMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->term);
          this->__isset.term = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->votedfor);
          this->__isset.votedfor = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t StablePBMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StablePBMeta");

  xfer += oprot->writeFieldBegin("term", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->term);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("votedfor", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->votedfor);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StablePBMeta &a, StablePBMeta &b) {
  using ::std::swap;
  swap(a.term, b.term);
  swap(a.votedfor, b.votedfor);
  swap(a.__isset, b.__isset);
}

StablePBMeta::StablePBMeta(const StablePBMeta& other16) {
  term = other16.term;
  votedfor = other16.votedfor;
  __isset = other16.__isset;
}
StablePBMeta& StablePBMeta::operator=(const StablePBMeta& other17) {
  term = other17.term;
  votedfor = other17.votedfor;
  __isset = other17.__isset;
  return *this;
}
void StablePBMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StablePBMeta(";
  out << "term=" << to_string(term);
  out << ", " << "votedfor=" << to_string(votedfor);
  out << ")";
}


LocalFileMeta::~LocalFileMeta() noexcept {
}

std::ostream& operator<<(std::ostream& out, const LocalFileMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LocalFileMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LocalFileMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LocalFileMeta");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LocalFileMeta &a, LocalFileMeta &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

LocalFileMeta::LocalFileMeta(const LocalFileMeta& other18) noexcept {
  (void) other18;
}
LocalFileMeta& LocalFileMeta::operator=(const LocalFileMeta& other19) noexcept {
  (void) other19;
  return *this;
}
void LocalFileMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LocalFileMeta(";
  out << ")";
}


LocalFile::~LocalFile() noexcept {
}


void LocalFile::__set_name(const std::string& val) {
  this->name = val;
}

void LocalFile::__set_meta(const LocalFileMeta& val) {
  this->meta = val;
__isset.meta = true;
}
std::ostream& operator<<(std::ostream& out, const LocalFile& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LocalFile::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->meta.read(iprot);
          this->__isset.meta = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LocalFile::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LocalFile");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.meta) {
    xfer += oprot->writeFieldBegin("meta", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->meta.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LocalFile &a, LocalFile &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.meta, b.meta);
  swap(a.__isset, b.__isset);
}

LocalFile::LocalFile(const LocalFile& other20) {
  name = other20.name;
  meta = other20.meta;
  __isset = other20.__isset;
}
LocalFile& LocalFile::operator=(const LocalFile& other21) {
  name = other21.name;
  meta = other21.meta;
  __isset = other21.__isset;
  return *this;
}
void LocalFile::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LocalFile(";
  out << "name=" << to_string(name);
  out << ", " << "meta="; (__isset.meta ? (out << to_string(meta)) : (out << "<null>"));
  out << ")";
}


LocalSnapshotPbMeta::~LocalSnapshotPbMeta() noexcept {
}


void LocalSnapshotPbMeta::__set_meta(const  ::braft::SnapshotMeta& val) {
  this->meta = val;
__isset.meta = true;
}

void LocalSnapshotPbMeta::__set_files(const std::vector<LocalFile> & val) {
  this->files = val;
}
std::ostream& operator<<(std::ostream& out, const LocalSnapshotPbMeta& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t LocalSnapshotPbMeta::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->meta.read(iprot);
          this->__isset.meta = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->files.clear();
            uint32_t _size22;
            ::apache::thrift::protocol::TType _etype25;
            xfer += iprot->readListBegin(_etype25, _size22);
            this->files.resize(_size22);
            uint32_t _i26;
            for (_i26 = 0; _i26 < _size22; ++_i26)
            {
              xfer += this->files[_i26].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.files = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t LocalSnapshotPbMeta::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("LocalSnapshotPbMeta");

  if (this->__isset.meta) {
    xfer += oprot->writeFieldBegin("meta", ::apache::thrift::protocol::T_STRUCT, 1);
    xfer += this->meta.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("files", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->files.size()));
    std::vector<LocalFile> ::const_iterator _iter27;
    for (_iter27 = this->files.begin(); _iter27 != this->files.end(); ++_iter27)
    {
      xfer += (*_iter27).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(LocalSnapshotPbMeta &a, LocalSnapshotPbMeta &b) {
  using ::std::swap;
  swap(a.meta, b.meta);
  swap(a.files, b.files);
  swap(a.__isset, b.__isset);
}

LocalSnapshotPbMeta::LocalSnapshotPbMeta(const LocalSnapshotPbMeta& other28) {
  meta = other28.meta;
  files = other28.files;
  __isset = other28.__isset;
}
LocalSnapshotPbMeta& LocalSnapshotPbMeta::operator=(const LocalSnapshotPbMeta& other29) {
  meta = other29.meta;
  files = other29.files;
  __isset = other29.__isset;
  return *this;
}
void LocalSnapshotPbMeta::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "LocalSnapshotPbMeta(";
  out << "meta="; (__isset.meta ? (out << to_string(meta)) : (out << "<null>"));
  out << ", " << "files=" << to_string(files);
  out << ")";
}

} // namespace
