/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef storage_TYPES_H
#define storage_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "base_types.h"


namespace braft {

class ConfigurationPBMeta;

class LogPBMeta;

class StablePBMeta;

class LocalFileMeta;

class LocalFile;

class LocalSnapshotPbMeta;

typedef struct _ConfigurationPBMeta__isset {
  _ConfigurationPBMeta__isset() : peers(false), old_peers(false) {}
  bool peers :1;
  bool old_peers :1;
} _ConfigurationPBMeta__isset;

/**
 * ConfigurationPBMeta - Configuration metadata stored on disk
 * Represents a single configuration (either old or new in joint consensus)
 */
class ConfigurationPBMeta : public virtual ::apache::thrift::TBase {
 public:

  ConfigurationPBMeta(const ConfigurationPBMeta&);
  ConfigurationPBMeta& operator=(const ConfigurationPBMeta&);
  ConfigurationPBMeta() noexcept {
  }

  virtual ~ConfigurationPBMeta() noexcept;
  std::vector<std::string>  peers;
  std::vector<std::string>  old_peers;

  _ConfigurationPBMeta__isset __isset;

  void __set_peers(const std::vector<std::string> & val);

  void __set_old_peers(const std::vector<std::string> & val);

  bool operator == (const ConfigurationPBMeta & rhs) const
  {
    if (!(peers == rhs.peers))
      return false;
    if (!(old_peers == rhs.old_peers))
      return false;
    return true;
  }
  bool operator != (const ConfigurationPBMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ConfigurationPBMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ConfigurationPBMeta &a, ConfigurationPBMeta &b);

std::ostream& operator<<(std::ostream& out, const ConfigurationPBMeta& obj);

typedef struct _LogPBMeta__isset {
  _LogPBMeta__isset() : first_log_index(false) {}
  bool first_log_index :1;
} _LogPBMeta__isset;

/**
 * LogPBMeta - Log file metadata
 * Stored in log file header
 */
class LogPBMeta : public virtual ::apache::thrift::TBase {
 public:

  LogPBMeta(const LogPBMeta&) noexcept;
  LogPBMeta& operator=(const LogPBMeta&) noexcept;
  LogPBMeta() noexcept
            : first_log_index(0) {
  }

  virtual ~LogPBMeta() noexcept;
  int64_t first_log_index;

  _LogPBMeta__isset __isset;

  void __set_first_log_index(const int64_t val);

  bool operator == (const LogPBMeta & rhs) const
  {
    if (!(first_log_index == rhs.first_log_index))
      return false;
    return true;
  }
  bool operator != (const LogPBMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LogPBMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LogPBMeta &a, LogPBMeta &b);

std::ostream& operator<<(std::ostream& out, const LogPBMeta& obj);

typedef struct _StablePBMeta__isset {
  _StablePBMeta__isset() : term(false), votedfor(false) {}
  bool term :1;
  bool votedfor :1;
} _StablePBMeta__isset;

/**
 * StablePBMeta - Stable storage metadata (persistent state)
 * Stored in stable storage (typically disk)
 * Contains the two persistent fields from Raft paper:
 * - currentTerm
 * - votedFor
 */
class StablePBMeta : public virtual ::apache::thrift::TBase {
 public:

  StablePBMeta(const StablePBMeta&);
  StablePBMeta& operator=(const StablePBMeta&);
  StablePBMeta() noexcept
               : term(0),
                 votedfor() {
  }

  virtual ~StablePBMeta() noexcept;
  int64_t term;
  std::string votedfor;

  _StablePBMeta__isset __isset;

  void __set_term(const int64_t val);

  void __set_votedfor(const std::string& val);

  bool operator == (const StablePBMeta & rhs) const
  {
    if (!(term == rhs.term))
      return false;
    if (!(votedfor == rhs.votedfor))
      return false;
    return true;
  }
  bool operator != (const StablePBMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StablePBMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(StablePBMeta &a, StablePBMeta &b);

std::ostream& operator<<(std::ostream& out, const StablePBMeta& obj);


/**
 * LocalFileMeta - Metadata for a single file in snapshot
 * Contains file-specific metadata like checksum, size, etc.
 * TODO: Add actual fields based on implementation needs
 */
class LocalFileMeta : public virtual ::apache::thrift::TBase {
 public:

  LocalFileMeta(const LocalFileMeta&) noexcept;
  LocalFileMeta& operator=(const LocalFileMeta&) noexcept;
  LocalFileMeta() noexcept {
  }

  virtual ~LocalFileMeta() noexcept;

  bool operator == (const LocalFileMeta & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LocalFileMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocalFileMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LocalFileMeta &a, LocalFileMeta &b);

std::ostream& operator<<(std::ostream& out, const LocalFileMeta& obj);

typedef struct _LocalFile__isset {
  _LocalFile__isset() : name(false), meta(false) {}
  bool name :1;
  bool meta :1;
} _LocalFile__isset;

/**
 * LocalFile - Represents a single file in a snapshot
 */
class LocalFile : public virtual ::apache::thrift::TBase {
 public:

  LocalFile(const LocalFile&);
  LocalFile& operator=(const LocalFile&);
  LocalFile() noexcept
            : name() {
  }

  virtual ~LocalFile() noexcept;
  std::string name;
  LocalFileMeta meta;

  _LocalFile__isset __isset;

  void __set_name(const std::string& val);

  void __set_meta(const LocalFileMeta& val);

  bool operator == (const LocalFile & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (__isset.meta != rhs.__isset.meta)
      return false;
    else if (__isset.meta && !(meta == rhs.meta))
      return false;
    return true;
  }
  bool operator != (const LocalFile &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocalFile & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LocalFile &a, LocalFile &b);

std::ostream& operator<<(std::ostream& out, const LocalFile& obj);

typedef struct _LocalSnapshotPbMeta__isset {
  _LocalSnapshotPbMeta__isset() : meta(false), files(false) {}
  bool meta :1;
  bool files :1;
} _LocalSnapshotPbMeta__isset;

/**
 * LocalSnapshotPbMeta - Local snapshot metadata
 * Stored in snapshot meta file
 * Contains information about files included in the snapshot
 */
class LocalSnapshotPbMeta : public virtual ::apache::thrift::TBase {
 public:

  LocalSnapshotPbMeta(const LocalSnapshotPbMeta&);
  LocalSnapshotPbMeta& operator=(const LocalSnapshotPbMeta&);
  LocalSnapshotPbMeta() noexcept {
  }

  virtual ~LocalSnapshotPbMeta() noexcept;
   ::braft::SnapshotMeta meta;
  std::vector<LocalFile>  files;

  _LocalSnapshotPbMeta__isset __isset;

  void __set_meta(const  ::braft::SnapshotMeta& val);

  void __set_files(const std::vector<LocalFile> & val);

  bool operator == (const LocalSnapshotPbMeta & rhs) const
  {
    if (__isset.meta != rhs.__isset.meta)
      return false;
    else if (__isset.meta && !(meta == rhs.meta))
      return false;
    if (!(files == rhs.files))
      return false;
    return true;
  }
  bool operator != (const LocalSnapshotPbMeta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocalSnapshotPbMeta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LocalSnapshotPbMeta &a, LocalSnapshotPbMeta &b);

std::ostream& operator<<(std::ostream& out, const LocalSnapshotPbMeta& obj);

} // namespace

#endif
